### PR TITLE
Private functions to public functions - animal life cycle

### PR DESCRIPTION
**Pull request by manfei-L**
This pull request is for unifying all functions in the animal life cycle section to public functions for consistency and clarity of the code.

### CODE REVIEW

**Comment by PooyaHekmati** [comment]
Hi Manfei, 
I do not see any problems with the code itself, but I am not sure why this change is needed in the first place. Why these private members are being converted to public? It seems some of them are more suited to be private. Can you provide more context?

**Comment by manfei-L** [comment]
Hi Pooya, we used private fuctions before and caused some duplicate fuctions in the reproduction and BW change for different classes. Furthermore, many of the changed functions, for example, those with estrus cycle determination, will be removed in further repro updates.

**Review by PooyaHekmati — APPROVED** [review]

**Comment by KFosterReed** [comment]
Looks good to me!

**Review by ltp23 — COMMENTED** [review]
It looks ok to me.

**Pull request merged**
