### PR TITLE
Merge new Crop and Soil code into the master branch

### LINKED ISSUE #715: Entirely replace old code with new code
This should be the very last task completed before trying to merge SC_redesign v1.0 with master (#223)

This entails replacing the entire RUFAS/routines/field folder with the SC_redesign folder and ensuring that all connections to the rest of the model are working.

### PR DESCRIPTION
**Pull request by Isgotkowitz**
This PR replaces the old Crop and Soil module with the redesigned, refactored, and overhauled Crop and Soil module.

Some testing stats:
- There are a total of 1937 tests for the new Crop and Soil module.
- 4880 total statements are contained in the new Crop and Soil module, with 6 untested by the test suite, which is ~99.88% test coverage.
- End-to-end testing has been conducted on this branch, which has consisted of running full simulations with the 6 complete input sets that are available (`animal_management.json`, `ARL.json`, `barnyard.json`, `multi_crop.json`, `swat.json`,  and `testing.json`). These simulations run and output data without crashing, but there are still numerous inaccuracies in the output which would be best addressed with a thorough evaluation and sensitivity analysis (IMO).

***NOTE*** The Crop and Soil module is the same as the Field module.

Notes for reviewers:
- `README.md` keeps automatically-changing itself, I think because the test coverage statistics change significantly with this PR but I'm not 100% sure about it.
- Lines 512 and 531 in `classes.py` (in `__init__()` and `advance()` respectively) have been changed, and they seem meaningful but were made almost a year ago by @rhensen and I am not sure if the changes should be kept or reverted.
- `OutputHandler` has been modified so that it does not interact at all with the new Crop and Soil module, though there was an effort to make it better as evidenced by the changes in `RUFAS/output_handler/reports/field_report.py`.
- `RUFAS/routines/feed/feed.py` has had a return statement added at the top of the method that handles interaction with the Field module, this seemed like the easiest and most convenient way to cut off the connection between them. It will also be the most easily reverted when the time comes to reintegrate the Feed and Field modules.
- Two new full input sets have been added: `swat.json` and `testing.json`. Also, `ARL.json` has had the simulation start delayed significantly, and `barnyard.json` has had a methane mitigation strategy added so the simulation will run. There are a number of other input files that have been added as well.
- All of the documentation from the `SC_redesign` branch has been saved in the `save_directory/docs_SC`. Some of it may not be necessary, but it seemed better to err on the side of saving more stuff.
- `requirements.txt` includes `juliandate` and `argparse` now as well.

### CODE REVIEW

**Comment by KFosterReed** [comment]
The overall structure looks good! It runs with all the provided json files and in general looks like it is in good shape. I added one question about the inputs/meta data in Allister's meta data PR: #685 [https://github.com/RuminantFarmSystems/MASM/pull/685](url). 

It seems like more of the outputs are 0 than I would expect and, in particular, the annual output folders do not seem to reflect the daily values. For example, if I run the ARL.json, the values in the the annual_surface_runoff_total csv are all 0 but the daily values in the accumulated_runoff file are not all zeros. 


I was also happy to see that I could implement a modified set of crop and soil inputs while also simulating animals with a modified animal_management input file. However, I am not sure that my goal to simulate manure application was achieved. Please see the added json files (note that these should not be pushed to the master branch). 

That is all I have for now!

**Comment by PooyaHekmati** [comment]
Hi Ed, I have a couple of questions about the structure of the repo being changed here. Why do we need a directory of called config? What kind of configuration is happening here? Why are the docs placed under the save directory `save_directory/docs_SC` ? Also, the fact the `output_handler` has changed is concerning. We are going to deprecate `output_handler` pretty soon. So we don't want to introduce new usages to it.

**Comment by Isgotkowitz** [comment]
> The overall structure looks good! It runs with all the provided json files and in general looks like it is in good shape. I added one question about the inputs/meta data in Allister's meta data PR: https://github.com/RuminantFarmSystems/MASM/pull/685 [https://github.com/RuminantFarmSystems/MASM/pull/685](https://github.com/RuminantFarmSystems/MASM/pull/url).

@KFosterReed Just looked into it and responded, I tagged Allister as well.

> It seems like more of the outputs are 0 than I would expect and, in particular, the annual output folders do not seem to reflect the daily values. For example, if I run the ARL.json, the values in the the annual_surface_runoff_total csv are all 0 but the daily values in the accumulated_runoff file are not all zeros.

Yes, there are definitely a lot of outputs that are not behaving as expected. For annual totals, I am confident that we can easily and quickly address them and get them actually recording what they should be recording. For a lot of other outputs though, they will take some significant effort to investigate and correct - we should discuss this more.

> I was also happy to see that I could implement a modified set of crop and soil inputs while also simulating animals with a modified animal_management input file. However, I am not sure that my goal to simulate manure application was achieved. Please see the added json files (note that these should not be pushed to the master branch).

I will look into why no manure is coming into the Field module - hopefully it will be a simple fix on our end, but it is possible that it is due to a bug in the Manure module in which case we (the Field module) would need to collaborate with Loi to identify what is going wrong.

My plan of action for right now is to investigate the manure issue, then discuss with Matthew how we can most efficiently go about addressing the incorrect behavior of the annual totals.

**Comment by KFosterReed** [comment]
Thanks for the response Ed! The manure application could be due to my use of the 'rotation_years' input instead of the 'years' input. I will modify and look into it :)

**Comment by Isgotkowitz** [comment]
> Hi Ed, I have a couple of questions about the structure of the repo being changed here. Why do we need a directory of called config? What kind of configuration is happening here? 

@PooyaHekmati in the `master` branch,  `config/` contains the file `global_variables.py`. I am not exactly sure how/if it gets used, but it looks like it may be pretty irrelevant at this point. I have removed the `__init__.py` file that was added in this PR and everything seems to run fine, but removing the `config/` directory entirely merits its own PR, if that is decided to be the best course of action.

> Why are the docs placed under the save directory save_directory/docs_SC ? 

Because I did not want to just delete them, and the `docs/` directory seemed to be dedicated to the Sphinx-generated documentation, so I did not want to muddy it with the miscellaneous Soil and Crop documentation. If there is a dedicated place I missed where they should go, just let me know and I will move them.

> Also, the fact the output_handler has changed is concerning. We are going to deprecate output_handler pretty soon. So we don't want to introduce new usages to it.

The changes to `output_handler.py` and `base_report.py` were to remove all connections to the Field module. The changes to `field_report.py` were made about a year ago, and I think were done with the hope that `OutputHandler` would continue to be used. Either way, the `OutputHandler` is fully disconnected from the new Crop and Soil code, and is ready (on the Crop and Soil end) to be deprecated.

**Comment by Isgotkowitz** [comment]
> The manure application could be due to my use of the 'rotation_years' input instead of the 'years' input. I will modify and look into it :)

I recommend just checking the output for `field_2`, because it uses `barnyard_schedule_field_management.json`, which uses the `year` field instead of `rotation_years`.

**Comment by PooyaHekmati** [comment]
> > Why are the docs placed under the save directory save_directory/docs_SC ?
> 
> Because I did not want to just delete them, and the `docs/` directory seemed to be dedicated to the Sphinx-generated documentation, so I did not want to muddy it with the miscellaneous Soil and Crop documentation. If there is a dedicated place I missed where they should go, just let me know and I will move them.
> 
@tomhuhh was/is leading the documentation effort. I think the docs should be in docs (not saves) if that makes sense.

**Comment by Isgotkowitz** [comment]
Update: 
- The recording of annual variables has been fixed.
- The manure-field connector is working, and manure is going through it when requested ****but only**** when there are animals being simulated (check the number of animals to be simulated in the animal input, and that `simulate_animals` is set to `true` in the config section of the input file). `barnyard_animal.json` is used as the animal configuration file for a lot of different simulations, but it doesn't actually simulate any animals.

**Review by PooyaHekmati — APPROVED** [review]

**Review by KFosterReed — APPROVED** [review]
So excited to get this merged in! Well done!!

**Pull request merged**
