### PR TITLE
update master 2 main

### PR DESCRIPTION
**Pull request by PooyaHekmati**
After renaming the default branch to the main, it is time to update our actions in the workflow.

### CODE REVIEW

**Review by Isgotkowitz — CHANGES_REQUESTED** [review]
`lint_branch_changes.sh` and `lint_branch_changes.bat` need to have master changed to main. Also looks like the CodeFactor workflow is not running.

**Review by Isgotkowitz — CHANGES_REQUESTED** [review]
`lint_branch_changes.bat` still needs to be updated.

**Comment by PooyaHekmati** [comment]
> `lint_branch_changes.bat` still needs to be updated.

I had changed but it was not saved. It should be good now.

**Comment by PooyaHekmati** [comment]
Forcing the merge as it is an urgent case.

**Review by Isgotkowitz — COMMENTED** [review]
Retroactive approval. Seems like everything is in good working order except the CodeFactor test

**Comment by PooyaHekmati** [comment]
> Retroactive approval. Seems like everything is in good working order except the CodeFactor test

That needs to be fixed in codefactore. I think we should depreciate it anyways.

**Pull request merged**
