### PR TITLE
Animal management refactor #1

### PR DESCRIPTION
**Pull request by ancheypeng**
This pull request adds unit tests for the following functions in the AnimalManagement class:

- avg_pen_dist
- clear_pens
- calc_avg_growth
- _calc_p_comp

Some refactoring was also done in the functions as well as the overall class.

### CODE REVIEW

**Review by PooyaHekmati — APPROVED** [review]
I do not see why this code cannot go through from SWE persepective. I approve the PR but I would like to have a subject matter expert's approval as well.

**Review by militsasotirova — APPROVED** [review]
Everything looks good to me! I like the way you re-organized the p_comp's. My only comment is that there seems to be a conflict with requirements.txt.

**Review by ltp23 — APPROVED** [review]
Hi Anchey, all tests passed for me. Thank you for your good work!

I like the use of sum() and other similar functions along with a list comprehension. I also like the generic function `create_mock_object_list`. I'm usually a fan of generics. I think for Mock and MagicMock objects you could impose certain specification restriction onto them like this `pen = Mock(spec=Pen)`, so that those mock objects can behave sorta like real objects. An advantage of this is accessing an undefined attribute should raise an error. For `mock_pens` and `mock_animals`, I think you could tweak them a little bit to make the return types become `List[Pen]` and `List[AnimalBase]`. `List[MagicMock]` reads somewhat odd or maybe it's just me. 

Also, my quirk in naming tests is to follow something along this format `test_<method>_should_<expect_something>_given_<some_input>` whenever possible. For example, I could split your `test_calc_p_comp` into `test_cal_p_comp_should_get_0_given_empty_list_of_animals` and `test_calc_p_comp_should_get_correct_p_comp_given_valid_list_of_animals`. I know those test names are lengthy and cumbersome. I think this is helpful when you have several ways to test something but are not sure how to name them.

**Comment by PooyaHekmati** [comment]
> Hi Anchey, all tests passed for me. Thank you for your good work!
> 
> I like the use of sum() and other similar functions along with a list comprehension. I also like the generic function `create_mock_object_list`. I'm usually a fan of generics. I think for Mock and MagicMock objects you could impose certain specification restriction onto them like this `pen = Mock(spec=Pen)`, so that those mock objects can behave sorta like real objects. An advantage of this is accessing an undefined attribute should raise an error. For `mock_pens` and `mock_animals`, I think you could tweak them a little bit to make the return types become `List[Pen]` and `List[AnimalBase]`. `List[MagicMock]` reads somewhat odd or maybe it's just me.
> 
> Also, my quirk in naming tests is to follow something along this format `test_<method>_should_<expect_something>_given_<some_input>` whenever possible. For example, I could split your `test_calc_p_comp` into `test_cal_p_comp_should_get_0_given_empty_list_of_animals` and `test_calc_p_comp_should_get_correct_p_comp_given_valid_list_of_animals`. I know those test names are lengthy and cumbersome. I think this is helpful when you have several ways to test something but are not sure how to name them.

Nice! I like the detailed explanation you provided. I also liked that you approved the pr as you didn't see any major issues, but provided your opinion and trusted that Anchey will take a second look. This is kind of behavior that we need to emphasize on.

**Comment by ancheypeng** [comment]
> Hi Anchey, all tests passed for me. Thank you for your good work!
> 
> I like the use of sum() and other similar functions along with a list comprehension. I also like the generic function `create_mock_object_list`. I'm usually a fan of generics. I think for Mock and MagicMock objects you could impose certain specification restriction onto them like this `pen = Mock(spec=Pen)`, so that those mock objects can behave sorta like real objects. An advantage of this is accessing an undefined attribute should raise an error. For `mock_pens` and `mock_animals`, I think you could tweak them a little bit to make the return types become `List[Pen]` and `List[AnimalBase]`. `List[MagicMock]` reads somewhat odd or maybe it's just me.
> 
> Also, my quirk in naming tests is to follow something along this format `test_<method>_should_<expect_something>_given_<some_input>` whenever possible. For example, I could split your `test_calc_p_comp` into `test_cal_p_comp_should_get_0_given_empty_list_of_animals` and `test_calc_p_comp_should_get_correct_p_comp_given_valid_list_of_animals`. I know those test names are lengthy and cumbersome. I think this is helpful when you have several ways to test something but are not sure how to name them.

Thank you for your review and advice! I think I will leave the code as-is for now just because of the time constraint and finals coming up, but for the next PR, I will incorporate some of your suggestions into the existing unit tests and any new ones I create.

**Review by KFosterReed — APPROVED** [review]
This refactoring looks good to me! I checked the outputs and they are the same as before refactoring so that looks good to me!

**Comment by KFosterReed** [comment]
@ancheypeng is there something that needs to be done on this pull request before it is merged in?

**Comment by ancheypeng** [comment]
> @ancheypeng is there something that needs to be done on this pull request before it is merged in?

I don't think so, it should be ready to merge!

**Pull request merged**
