### PR TITLE
Added two new diets

### PR DESCRIPTION
**Pull request by tomhuhh**
The NE diet is based on one of the diets from Edward; the W diet is based on the UDR test google sheet.

### CODE REVIEW

**Comment by tomhuhh** [comment]
I tested with these two diets and they work fine. However, in the output, it shows that the requirements below are not met. 
- "NEmact_constraint",
- "NDF_constraint_upper"

**Comment by JoeWaddell** [comment]
> I tested with these two diets and they work fine. However, in the output, it shows that the requirements below are not met.
> 
>     * "NEmact_constraint",
> 
>     * "NDF_constraint_upper"

After testing I see this behavior is the same for both diets.

For the failed constraints for pen2, reviewing the user-defined values, they don't total 100%! That's why it's giving the NEmact and NDF failures.
Pen 2 fails but uses the default ration because there are no methods to reduce requirements for animals that aren't lactating. See Issue #577 

Pen 3 fails for `total_energy` just once: so after one reduction in lactation, it passes. This single reduction (which doesn't greatly affect overall production) may be alleviated when we have the NASEM nutrient values in RuFaS, as these may be assuming slightly different files.

**Comment by tomhuhh** [comment]
Thanks for catching that Joe! If you are okay with these two diets, we can merge them into Masters. Thanks!

**Comment by JoeWaddell** [comment]
I've updated the dry cow ration so that hay forage makes up the rest of the ration (since it previously totaled less than 100%), and I've deleted the Western Diet (I have a local copy), so that we keep the number of diets on master relatively low (following discussion with @KFosterReed ).

**Comment by JoeWaddell** [comment]
Since output handler has now been deprecated, I've also removed the `quick_ration_analysis.py` script in this same PR, since it was dependent on the old structure of ration CSVs. I have a local copy to modify/reinstate once CSVs are being printed again.

**Review by JoeWaddell — APPROVED** [review]
Harder to evaluate after deprecation of output handler and lack of CSVs, but relevant info is in the output manager, and this seems to be a good "default" for testing/development purposes. Should close https://github.com/RuminantFarmSystems/MASM/issues/755

**Review by KFosterReed — APPROVED** [review]

**Pull request merged**
