### PR TITLE
Bookshelf: Generalized sensitivity analysis

### PR DESCRIPTION
**Pull request by morrowcj**
# NOTE 

This PR will be split into multiple PRs. It is too large ATM. AND contains changes beyond those present in #402 

----

This PR will setup a generalized sensitivity analysis module to be used with RUFAS. I will adapt the tools that @JoeWaddell has created for the more general case. 

# Changes

Most of the changes are additions of reference files and can be ignored for the Review. The 3 files that should be reviewed are

* The `README.md` file, which contains information about the module generally
* The `generalized_sensitivity.py` file, which contains the relevant class.
* The `SC_sensitivity.md` file, which will serve as a design/plan for executing SA on the crop and soil modules. 

# Notes
This is just a draft for now. I wanted to make it available early so that feedback can be added at any stage. 
I'll convert to a full pull request once it is ready for review.

### CODE REVIEW

**Comment by JoeWaddell** [comment]
This is great! 

March 22nd onward I'll have this work as my priority again (finishing analyses for a conference abstract and review of another pending RuFaS PR in the meantime), so I should be able to streamline the .py files you references and get them uploaded here within a couple of days. I have no problem with uploading those draft files I sent, but for anyone else reading this - forgive me for embarrassing in-progress code! 

To give a quick overview of my plan: the idea is to have three main files that will mirror the general process: 1) Define the scope of the analysis, e.g. specify the input variables and the ranges over which you want to perform analyses, the outputs you want to analyze, and define the type of analysis and their associated attributes (number of runs, level of interaction effects to explore, etc); 2) Run RuFaS according to setup in step 1, either in a loop or in parallel, and; 3) Analyze the results of step 2.

Note: Both steps 2 and 3 will be performed given the output of a 'setup' JSON we'll generate in step 1, where initialization parameters are stored. 

Also: there will be a fourth file that's filled with helper functions, to streamline the three main scripts.

**Comment by morrowcj** [comment]
@JoeWaddell, we should talk again before you do too much additional work. I've been in the weeds of SALib and there's native support for parallelization and distribution within the package (it is hidden and experimental). I've begun conversations with the authors and I think I'll be able to get it to work. I also think I can greatly simplify your pipeline with the generalization I'm planning.

**Comment by morrowcj** [comment]
@JoeWaddell, as I was thinking about this, the developers wrote up a very handy help page for wrapping existing methods to be used with their package (for parallelization): 

https://salib.readthedocs.io/en/latest/user_guide/wrappers.html

**Comment by morrowcj** [comment]
this PR is superseded by #402 and is outdated.

**Pull request closed without merging**
