### PR TITLE
Update animal_module_reporter.py

### PR DESCRIPTION
**Pull request by tomhuhh**
This PR is to address issue #1142. It seems that there is an attempt to delete the key 'status' from the ration_per_animal dictionary, but that key doesn't exist in the dictionary, resulting in a KeyError.

Our solution is to check if the 'status' key exists before attempting to delete it. In this PR, we added the if statement for both 'status' and 'objective'. 

To validate the change, first grab the input files of farm 13 in pilot testing cohort 2 and run it on the main branch to repeat the error and then use this updated branch to run the same input files and you should expect no errors. 

Yet, we still need to review the code where the `ration_per_animal dictionary` is constructed or modified to understand why the 'status' key might be missing when it's expected. A comment from Joe: 'I think it's because it's inherited from a previous formulation or other animal'.

### CODE REVIEW

**Review by JoeWaddell — APPROVED** [review]
Good fix for catching edge case errors.

**Comment by PooyaHekmati** [comment]
> Yet, we still need to review the code where the `ration_per_animal dictionary` is constructed or modified to understand why the 'status' key might be missing when it's expected. A comment from Joe: 'I think it's because it's inherited from a previous formulation or other animal'.

This makes me a bit uncomfortable here. We need to understand both upstream and downstream impacts before making the change. In other words, 1, why is this happening in the first place? Is it a signal that something bigger is going on and we are not aware of it? 2, what happens downstream after we make this change? how does it effect other things?

**Comment by JoeWaddell** [comment]
@PooyaHekmati excellent points, I was too hasty in approving. I assumed it had to do with the hard-coded ration in calf.py #1137 (we had a conversation about this earlier), so my mistake! 

What I thought was happening is that folks wanted to hardcode in a different calf ration, which would throw an error here (if they didn't add the status and objective fields, which are only used in the optimization process). Calf ration formulation is a 'wish', so it's been backburnered. 

Now that I'm taking a closer look, @tomhuhh I cant' replicate the error on my end. Can you add the files to replicate it to this branch, so that we're all on the same page?

**Review by JoeWaddell — CHANGES_REQUESTED** [review]
See previous comment, can't replicate the outlined error.

**Comment by PooyaHekmati** [comment]
> @PooyaHekmati excellent points, I was too hasty in approving. I assumed it had to do with the hard-coded ration in calf.py #1137 (we had a conversation about this earlier), so my mistake!
> 
> What I thought was happening is that folks wanted to hardcode in a different calf ration, which would throw an error here (if they didn't add the status and objective fields, which are only used in the optimization process). Calf ration formulation is a 'wish', so it's been backburnered.
> 
> Now that I'm taking a closer look, @tomhuhh I cant' replicate the error on my end. Can you add the files to replicate it to this branch, so that we're all on the same page?

No problem at all @JoeWaddell, since PR 1000, we have started taking the Zen of Python more seriously. A few point from the Zen of Python:
_Errors should never pass silently._
_In the face of ambiguity, refuse the temptation to guess._
_Special cases aren't special enough to break the rules._

In cases like this PR, we have to be careful about the big picture. If it is possible, we have to work through the downstream and upstream systems first. If the issue is major and we can't afford to investigate the interconnected systems right now, we can snooze the alert for now by clearly documenting that xyz problem was observed and it was decided to silence it for now because of abc reason. The xyz problem needs to be revisited by doing this and that.

**Comment by tomhuhh** [comment]
I was not able to replicate the error either. 

However, as @JoeWaddell verified, there is no future concerns associated with the error that I encountered because the `Del` statement deals with a copy of the `ration_per_animal`. 

Closing this PR and the related issue.

**Pull request closed without merging**
