### PR TITLE
Better integrate `flake8` into RuFaS

### PR DESCRIPTION
**Pull request by Isgotkowitz**
This PR contains a configuration file for `flake8`, a script for running `flake8` locally in a convenient and precise way, and a modified GitHub action workflow for linting PRs in a more precise way.

- The `flake8` config file has been added so that linting is done with consistent settings.
- The GitHub action now only lints Python files that have been added or modified in the PR.
  - This was achieved using the [get-changed-files](https://github.com/marketplace/actions/get-all-changed-files) action developed by jitterbit.
- `cleanup.sh` has been added here from #429 and renamed as `lint_branch_changes.sh` (there is also a Batch file version), it does the same thing as the GitHub action - just locally.
  - Also an additional check has been added so if no Python files have been modified in the branch yet then no files are checked.

A wiki page has also been written describing how to use `flake8` in RuFaS - it should be consistent with all the tools/configurations added in this PR.

### CODE REVIEW

**Comment by PooyaHekmati** [comment]
Can you please add this configuration to the listing workflow as well to make sure github is using the same thing?

**Comment by ew3361zh** [comment]
We'd talked about this in #429 and discussed a script that people could run to check for and correct flake8 errors  locally before merging. Looking back at it I think the script wasn't working on PCs and/or in PyCharm so perhaps there is some other tool people can use individually but we could make some recommendations.

I do think the flake8_instructions.md file we were writing to eventually be in the Wiki was good for at least getting people started on using and installing flake8 and explaining what it is. Perhaps the only changes I'd make to that would be adding the above-mentioned suggestions for ways that people can run flake8 checks locally on various OS and IDEs.

My suggestions:
1. Close out #429 without merging since there were some examples of correcting flake8 issues that are (likely) long outdated.
2. Follow Pooya's request to add this to the linting workflow in GitHub.
3. Add some instructions on how to align their local linters with flake8. I think if the goal is to have better alignment of linting practices across the board, it would be good to ensure people know how to incorporate and use flake8 locally.

**Comment by Isgotkowitz** [comment]
Should `flake8` be added to the requirements file? 

Edit: done

**Review by allisterakun — APPROVED** [review]
Changes look good, but one question: It looks like you are not using the `cleanup.sh` script in the GitAction. Is it still necessary to keep the file in the repository?

**Comment by Isgotkowitz** [comment]
> Changes look good, but one question: It looks like you are not using the `cleanup.sh` script in the GitAction. Is it still necessary to keep the file in the repository?

Yes. `cleanup.sh` does the same thing as the GitHub Action, but is intended to be used as a developer productivity tool that is run locally. It lets people catch errors as they make changes, instead of having to go through the whole cycle of committing, pushing, and waiting for the GitHub action to run.

**Review by ew3361zh — APPROVED** [review]
Looks good overall and working well for me locally. A few things I'd want to make sure were in place before merging:

1. Are all linting violations now going to prevent merging? I forget where we landed on this because I know you were considering the potential affect on workflow - especially on some of the older files that are being refactored piecemeal.
2. Has the cleanup.sh been successfully tested on different OS and IDEs?
3. Are there any potential conflicts with built-in linters like what PyCharm has and incorporating flake8 or with other linters people have installed? i.e. will people need to do some work to disable their current linters? This may be something that has to come up organically since I don't think I've seen any issues like this (and it may not even be an issue!).
4. I have some feedback about things I'd like to see in the Wiki/wording in the Wiki on some things.

Really nice work, Ed!

**Comment by Isgotkowitz** [comment]
> Looks good overall and working well for me locally. A few things I'd want to make sure were in place before merging:
> 1. Are all linting violations now going to prevent merging? I forget where we landed on this because I know you were considering the potential affect on workflow - especially on some of the older files that are being refactored piecemeal.
> 2. Has the cleanup.sh been successfully tested on different OS and IDEs?
> 3. Are there any potential conflicts with built-in linters like what PyCharm has and incorporating flake8 or with other linters people have installed? i.e. will people need to do some work to disable their current linters? This may be something that has to come up organically since I don't think I've seen any issues like this (and it may not even be an issue!).
> 4. I have some feedback about things I'd like to see in the Wiki/wording in the Wiki on some things.
>
> Really nice work, Ed!

@ew3361zh thank you:)
1. Any linting violations in Python files _added or modified_ in the PR will prevent merging. When this gets merged it should be made clear through the general slack channel that there may be some old linting violations that would be inappropriate to try and fold in with a PR, in which case the author should reach out to someone with admin privileges and override the linting failure and allow the PR to be merged.
2. `cleanup.sh` runs for me on Ubuntu, if it works for you then I think it passes Mac, the issue is Windows. It is possible to run it on both GitBash (USDA-approved) and WSL (not USDA-approved), but that requires switching to a different shell. In the Windows command line, it is possible to run `bash <bash command>`, but I have not been able to get it working with `cleanup.sh`. I think this is acceptable for now, and we can work on debugging it as people start using it across a more diverse array of environments. As for IDEs, I'm not sure, but I think people should be able to run it from whatever terminal feature their IDE has.
3. I am not sure if there will be errors with other linters, I don't think there will be many. So far most of the linting suggestions PyCharm makes have been correct and helps format files easily, but there are a few instances where PyCharm gets it wrong and I have to manually fix errors. Hasn't been a big issue yet, so I think any issues with it will come up organically.
4. Please edit the wiki freely, the more time that everyone can put into it the better.

**Review by PooyaHekmati — CHANGES_REQUESTED** [review]
1. Can we rename cleanup.sh to something more meaningful? Cleaning up what? What happens if I don't clean up? etc... something like lint_w_flake8.sh should do.
2. Windows machines are not natively capable of running shell files. The user needs to use either WSL or Git Bash, both of which are not intuitive and easy for non-technical users. Can we add a .bat file version of this shell file so Windows users can run that? This probably will work (needs confirmation):

```
@echo off
REM This is a Windows batch script equivalent to your shell script

REM Function to display usage
:display_usage
echo Usage: cleanup.bat [BASEBRANCH]
echo Lint all files different between current branch and BASEBRANCH with Flake8.
echo.
echo With no BASEBRANCH, compare the current branch to master.
goto :eof

REM Check the number of command line arguments
IF "%~1"=="" (
    set "base_branch=master"
) ELSE IF "%~2"=="" (
    set "base_branch=%~1"
) ELSE (
    call :display_usage
    exit /b 1
)

REM Get the list of changed Python files
FOR /F "delims=" %%G IN ('git diff --name-only ^(^git merge-base %base_branch% HEAD^) ^| findstr /R "\.py$"') DO (
    set "changed_files=!changed_files! %%G"
)

REM Exit if there are no Python files to lint
IF "%changed_files%"=="" (
    exit /b 0
)

REM Run Flake8 on the changed Python files
flake8 %changed_files%
```
4. The commands in the wiki page start with $ which is not supported by Windows. Can we have a separate section for Windows users? 
The current structure of this wiki is:

> What and Why
> How
>> Automatic
>>> Note:
>>
>> Manual
>>> cleanup.sh
>>
>> Installation
>> Configuration
>
> External Resources

I propose changing it to:
> What and Why -> Keep it the same, add a link to the relevant section in the onboarding wiki
> How
>> Automatic -> Keep it the same, add screenshots of the next steps (after the user clicks on details), highlight the relevant parts of the screenshots with arrows and bounding boxes (see Output Manager's wiki for ref)
>>
>> Manual
>>> Integrate the config file with your IDE and use `format document` option
>>>> VScode integration
>>>> Pycharm integraion
>>>
>>> Use the Command Line
>>>> Quick Start -> See below
>>>> Use cleanup.sh -> rename the file?

The quick start can be:

# Quick Start

## For Windows Users


### Using Command Prompt

1. **Open Command Prompt**: Press `Win + R`, type `cmd`, and press Enter.
  Or **Open PowerShell**: Hold the Shift key down, and right-click in the directory containing your RUFAS project, and choose "Open PowerShell window Here."

3. **Install Flake8**: Open Git Bash (right-click in the directory containing your RUFAS project and choose "Git Bash Here") and run:

   ```sh
   pip install flake8
   ```
    Or if you prefer to install and upgrade all of RUFAS requirements, run:
   ```sh
   pip install -r requirements.txt -U
   ```
   
4. **Navigate to the RUFAS Directory**: Use the `cd` command to navigate to your RUFAS project directory. For example:

   ```sh
   cd path\to\your\RUFAS
   ```

5. **Run Flake8 with default settings on All Python Files in the RUFAS Directory and Subdirectories**:

   ```sh
   flake8 .
   ```

6. **Run Flake8 with the Configuration from .flake8 File**:

   ```sh
   flake8 --config .flake8 .
   ```

### Using Git Bash

1. **Install Git for Windows**: Download and install Git for Windows from the official website: [Git for Windows](https://gitforwindows.org/).

2. **Open Git Bash**: Right-click in the directory containing your RUFAS project and choose "Git Bash Here."

3. **Install Flake8**: Open Git Bash (right-click in the directory containing your RUFAS project and choose "Git Bash Here") and run:

   ```sh
   pip install flake8
   ```
   Or if you prefer to install and upgrade all of RUFAS requirements, run:
   ```sh
   pip install -r requirements.txt -U
   ```

4. **Run Flake8 with default settings on All Python Files in the RUFAS Directory and Subdirectories**:

   ```sh
   flake8 .
   ```

5. **Run Flake8 with the Configuration from .flake8 File**:

   ```sh
   flake8 --config .flake8 .
   ```

## For Linux Users

### Installation

1. **Navigate to the RUFAS Directory**: Use the `cd` command to navigate to your RUFAS project directory. For example:

   ```sh
   $ cd /path/to/your/RUFAS
   ```
   
2. **Install Flake8**: Open your terminal and run:

   ```sh
   $ pip install flake8
   ```
   Or if you prefer to install and upgrade all of RUFAS requirements, run:
   ```sh
   $ pip install -r requirements.txt -U
   ```
   
3. **Run Flake8 with default settings on All Python Files in the RUFAS Directory and Subdirectories**:

   ```sh
   $ flake8 .
   ```

4. **Run Flake8 with the Configuration from .flake8 File**:

   ```sh
   $ flake8 --config .flake8 .
   ```

## For macOS Users

### Installation

1. **Navigate to the RUFAS Directory**: Use the `cd` command to navigate to your RUFAS project directory. For example:

   ```sh
   cd /path/to/your/RUFAS
   ```

2. **Install Flake8**: Open your terminal and run:

   ```sh
   pip install flake8
   ```
   Or if you prefer to install and upgrade all of RUFAS requirements, run:
   ```sh
   pip install -r requirements.txt -U
   ```
   
3. **Run Flake8 with dfeault settings on All Python Files in RUFAS Directory and Subdirectories**:

   ```sh
   flake8 .
   ```

4. **Run Flake8 with the Configuration from .flake8 File**:

   ```sh
   flake8 --config .flake8 .
   ```

**Comment by Isgotkowitz** [comment]
> 1. Can we rename cleanup.sh to something more meaningful? Cleaning up what? What happens if I don't clean up? etc... something like lint_w_flake8.sh should do.
> 2. Windows machines are not natively capable of running shell files. The user needs to use either WSL or Git Bash, both of which are not intuitive and easy for non-technical users. Can we add a .bat file version of this shell file so Windows users can run that? ...
> 3. The commands in the wiki page start with $ which is not supported by Windows. Can we have a separate section for Windows users? ...

@PooyaHekmati 
1. I went with `lint_branch_changes.sh` and `lint_branch_changes.bat`. Is this an alright naming structure?
2. Added. It has not been thoroughly tested, but I'll work with it some more and ask some other Windows users to try it.
3. I'll work on the Quickstart section and rewrite the Script usage section.

**Review by PooyaHekmati — APPROVED** [review]
[LGTM](https://lgtm.lol/i/800)

**Pull request merged**
