### PR TITLE
Heifer ration tester

### PR DESCRIPTION
**Pull request by Fjordrunner**
This pull request addresses issues involving ration and feed calculations for individual pens within the model. It also aims to compartmentalize the feeds by animal class instead of a farm-wide grouping. 

This pull request will contain all of the changes from the original heifer ration branch. Any details regarding those specific changes can be found here: https://github.com/RuminantFarmSystems/MASM/pull/95.

Problem: 

The main problem that heifer_ration_tester sought to fix was the way that the model handled ration outputs, which were not pen specific. This defeats the purpose of having separate .csv files for each pen’s ration, as they all output the same ration report’s even though each pen would have some individual report based on the animals stored in that pen. 

Fix:

The fix to the problem listed above was to first split up the feeds by animal type. The feed input files have an additional 4 fields, one for each animal type, so that the feed can be subset accordingly using the corresponding AnimalCombination for each pen. This change also reworked the output handler for pens, relying on the individual ration of any given pen rather than the farm’s total ration, which included feeds not used for all pens. This eliminates the occurrence of irrelevant feeds in pen-specific outputs and provides users with an output that is more specific to every individual pen. 

Additional Changes:
- Converted animal_groups and valid_animal_groups to AnimalCombination Enum
- Added four fields to panke_buisse_feed.json for the four animal types within the scope of the model
- Added new instance attributes to Feed to account for the new four fields in the .json file listed above
- Split farm grown feeds and purchased feeds into two separate instance attributes in Feed class
- Hardcoded ration function for calves was added in calf_ration.py to fix some errors in the calf pen ration outputs

### CODE REVIEW

**Review by PooyaHekmati — APPROVED** [review]
Considering the priority and situation of this PR, I do not see any immediate changes needed. Once subject matter experts approve, this code should be good to land.

**Comment by KFosterReed** [comment]
This seems to be mostly functioning as desired! I have a couple of questions though: 

1. What is the purpose of the pens_by_animal_combination attribute? It is continuously appended to throughout the simulation so gets longer and longer. I ran a 2 year simulation in which there was intentionally not enough stalls for one of the groups and that group ended up having over 100 pens in their pens_by_animal_combination list. 
2. Sometimes when new pens are initialized, not all of the pens are reported in the output reports. For example, if I change the number of stalls in the lactating cow pen ('pen3') to be 700, by the end of the simulation, there are a total of 8 pens (pen.all_pen_ids length is 8) but there are only 4 pens that are reported in the outputs. Any thoughts?

**Comment by ancheypeng** [comment]
@KFosterReed I'm not sure what pens_by_animal_combination does, I believe it was something added by Chris. Originally, when I started working on the AnimalManagement class, it was named pens_by_animal_group, but after switching to the AnimalCombination Enum, I renamed it to pens_by_animal_combination. There are quite a few dictionaries throughout the class that don't seem to have a clear purpose documented. I think I mentioned that this was one of them in one of our meetings, and I think you mentioned that it might have been documented in the original heifer_ration PR. I checked the PR description word doc, and I don't think it mentioned anything about this dictionary or any of the others.

Simon and I just did some quick testing, and it seems like the reports are created before any of the extra pens are created or any of the daily updates run. I'm not sure how this affects the rest of the data, and we will look into it a bit more later. We can also talk about it during our meeting tomorrow.

**Comment by KFosterReed** [comment]
Thanks for the info @ancheypeng. It seems like the the pens_by_animal_combination list is doing the same thing as the separate lists created on lines 530-533 in animal_management.py but they are both used separately in different functions. I think I found a 'quick fix' by resetting the combined list right below the old lists so now it doesn't grow continuously. However, in the refactoring process I think these two should be combined. I will make a Git Issue for this. 

For the pen reporting, that makes a lot of sense. If the number of stalls is too small for the first set of animals, then a new pen is created and there is a report for that pen. However, if the number of animals in a group grows throughout the simulation and a new pen is created after day 1, then there is no report for that pen. I will make another Git issue for this.

**Review by KFosterReed — APPROVED** [review]
I ran all the combinations of animals and this is mostly functioning as desired! A few things to follow up on are in new Issues but overall great work. On to the refactoring!

**Comment by militsasotirova** [comment]
The code itself looks good to me! One small thing - I had made a PR during the fix-a-thon to add DS Store to the .gitignore. It looks like this file is re-introduced here (I'm guessing it was in there from before and not deleting it when the merge from master happened is the problem). Could you delete all the .DS_Store files?

**Comment by KFosterReed** [comment]
> The code itself looks good to me! One small thing - I had made a PR during the fix-a-thon to add DS Store to the .gitignore. It looks like this file is re-introduced here (I'm guessing it was in there from before and not deleting it when the merge from master happened is the problem). Could you delete all the .DS_Store files?

Good catch @militsasotirova! Once those files are deleted, you are cleared to merge!

**Review by militsasotirova — APPROVED** [review]

**Pull request merged**
