### PR TITLE
Feed Quality PR 1

### PR DESCRIPTION
**Pull request by ew3361zh**
**What:**
This PR is the first in the process of breaking up [PR 187](https://github.com/RuminantFarmSystems/MASM/pull/187) into smaller and more focused pieces.

This first one is focused on issues [#129](https://github.com/RuminantFarmSystems/MASM/issues/129), [#186](https://github.com/RuminantFarmSystems/MASM/issues/186) and [#111](https://github.com/RuminantFarmSystems/MASM/issues/111). 

**Why:**
While most of the work was approved in terms of functionality in PR 187, there were too many separate issues it addressed so it seemed to stray too far from single-responsibility principles to be merged all at once. These issues were difficult to separate into distinct PRs as they were all entangled with how the json input files were set up and how they were parsing the feed quality data called on by those json input files. While there are a number of files changed in this PR, the majority of them are small and similar changes to json files. Hopefully this is a significant enough PR on its own to warrant the limited scope of what it does while still functioning and also being reduced in complexity enough to make it signficantly simplified enough to warrant one PR.

**How:**
For issue 111 (Bug with feed storage_report specifically with being able to run a simulation without creating this report): this was corrected mainly in the various json files

For issue 129 (Cannot use feeds with different qualities due to reporting issue): This was solved by adding and incorporating the feed_typed_dicts.py module as well as some fixes to the feed.py module, many of which see like they were accomplished in [this commit](https://github.com/RuminantFarmSystems/MASM/pull/187/commits/98669dd2079d9466ca97eb589969f92ea6aef099) to PR 187 (for reference).

Finally for issue 186 (Graphics Production Error with Certain Feeds to to improper filename parsing): this seemed mainly having to do with specifying a file extentsion type in the graphics.py mp.savefig path. Once .png was added, the mp library knew how to handle it. 

This branch was tested with master and pytest and ran well with these changes.

### CODE REVIEW

**Review by ancheypeng — APPROVED** [review]
Looks good to me!

**Comment by KFosterReed** [comment]
image
Overall this makes sense and I think is almost there. I am getting this error when I run the model for longer (change the length of the simulation time in animal_management.json to running from 2009-2015 instead of just a few days in 2009).

I'll come back to it tomorrow (Tuesday) and see if I have any more suggestions about what is going on here.

**Comment by ew3361zh** [comment]
> image Overall this makes sense and I think is almost there. I am getting this error when I run the model for longer (change the length of the simulation time in animal_management.json to running from 2009-2015 instead of just a few days in 2009).
> 
> I'll come back to it tomorrow (Tuesday) and see if I have any more suggestions about what is going on here.

Thanks, Kristan, I'll run some tests but I think the changes that address the division by zero errors that I saw popping up in PR 187 commits are in [PR 268](https://github.com/RuminantFarmSystems/MASM/pull/268) (the second of the two PRs breaking up PR 187).

**Comment by ew3361zh** [comment]
@KFosterReed I was not able to recreate this error on my side for this PR by adjusting the config start and end dates  - could you share the input json file you used and the settings you changed?

**Review by KFosterReed — COMMENTED** [review]
My error was coming from running a small herd size but does not occur with a larger herd. Approving this pull request knowing that the divison by zero error has a permanent fix in the second part of this pull request

**Review by KFosterReed — APPROVED** [review]

**Pull request merged**
