### PR TITLE
init issue templates

### PR DESCRIPTION
**Pull request by PooyaHekmati**
Created templates for issues.

### CODE REVIEW

**Review by KFosterReed — COMMENTED** [review]
These look good in general. A couple of questions: 
1) is there a reason the comments are designated by hashes in one and asterixis in the other? 
2) Does it make sense to have the intro values (name, about, title, labels, and assignees) in all issues? (i.e. add it to the issue template as well?)
3) Can you provide a description for labels and assignees? Also, what is the difference between name and title?

**Comment by PooyaHekmati** [comment]
> These look good in general. A couple of questions:
> 
> 1. is there a reason the comments are designated by hashes in one and asterixis in the other?
These are markdown (MD) files, in which hashes show headers (# for h1, ## for h2, ### for h3 and so on),  ends the comment, and --- is used for tables. On GitHub web, please switch to issue_template branch and go to 
.github/ISSUE_TEMPLATE and see how these files are rendered. readme.md uses the same syntax.

> 2. Does it make sense to have the intro values (name, about, title, labels, and assignees) in all issues? (i.e. add it to the issue template as well?)
I added them.

> 3. Can you provide a description for labels and assignees? Also, what is the difference between name and title?
When creating an issue, one can add labels to it. We currently (by default) have 9 labels in this repo. You can see them under the issues tab. Assignees are the persons who are working on this issue. The name is showing the nature of the work (bug report, feature request, etc.) while the title is tied to the content of the issue, e.g., function x in module y not working.

**Review by militsasotirova — APPROVED** [review]
Looks good to me!

**Review by KFosterReed — APPROVED** [review]
Thanks for the clarifications! It looks good :)

**Pull request merged**
