### PR TITLE
Donovan revert crop

### PR DESCRIPTION
**Pull request by wmaxdonovan**
Reverted accidental reversion, and then reverted unintended file upload in the crop module.

### CODE REVIEW

**Comment by mmotew** [comment]
These changes look correct. They revert all the incorrect commits and restore the code to the proper state. I approve the merge.

**Comment by KFosterReed** [comment]
I approve both commits. It took me a minute to understand the double reversion, but I got there  :) 

We should discuss the revert option in our meeting next week!

**Review by KFosterReed — APPROVED** [review]

**Comment by KFosterReed** [comment]
I approved the changes. Although Missy commented her approval, I don't see her official approval so it still says merging is blocked. Feel free to merge when you're ready!

**Review by mmotew — APPROVED** [review]
I have checked out this code and it appears to be the same as the previous stable version. It also runs fine.

**Pull request merged**
