### PR TITLE
Fixed recording of phosphorus from surface soil layer

### LINKED ISSUE #1566: Available Phosphorus Pool needs to be reset to 0 after "watering" (rainfall or irrigation)
There are two pools of phosphorus on the soil surface (available and recalcitrant) and phosphorus doesn't appear to be moving out of them quite properly into the soil. 

## Expected Behavior
There are two pools of phosphorus on the soil surface (available and recalcitrant. When phosphorus is applied 75% should go to the available pool (this is happening fertilizer.py line 164) and 25% goes to the recalcitrant pool. When it rains the FIRST time, all of the available_phosphorus should be released into the soil and the available_phosphorus pool should go to 0 (because all of it goes to the soil). In all subsequent rainfalls, the recalcitrant_phosphorus pool is the one that is impacted. The second rainfall 40% of the recalictrant_phosphorus goes into the soil and in all subsequent rainfalls 7.5% of the remaining phosphorus in the recalcitrant pool should go into the soil. 

## Current Behavior
Currently, it seems we don't set the available_phosphorus_pool to 0 when we move the phosphorus from this pool to the soil. We put phosphorus in the soil, but it never leaves the available_phosphorus_pool and is resulting in a lot of runoff. 

It also appears that while 

## Possible Solution
Adding a reset of the available_phosphorus_pool to 0 when a rainfall/irrigation event occurs would be great. During rainfall events only the recalcitrant phosphorus pool should be the phosphorus that is accessible to becoming solubilized. It seems like we just have a generic "phosphorus_pool" instead of just the recalcitrant_phosphorus_pool that can become solubilized.

The second piece, I can't seem to identify in the code at all is that for the partitioning of the recalcitrant pool to the soil in subsequent rainfall events. I think we need to add this partitioning, 40% on the second rainfall following application and 7.5% for every additional rainfall event. 

Lastly, irrigation needs to be considered a "rainfall" event, not just true precipitation that falls from the sky. 

## Steps to Reproduce
I'm working through c1f2_wcrops_metadata when I found this error. 

## Context (Environment)
My phosphorus runoff is 500x what it should be! 

## Detailed Description
I'm proposing we 1) broaden rainfall to be irrigation or rainfall 2) "zero" the available_phosphorus_pool after the first rainfall/irrigation event as all of it should go to the soil layers below the surface and 3) partition the recalcitrant_phosphorus_pool for each rainfall/irrigation event following the first one such that the size of that pool decreases and less is available for solubilization and runoff. 

## Possible Implementation
I think these items will occur in the fertilizer.py file 

## Target Deadline
Monday, around noontime, if possible.

### PR DESCRIPTION
**Pull request by Isgotkowitz**
Fixes the runoff phosphorus amount being recorded by the field size (converting kg/ha to kg when it should not have been). This change has been verified by checking both the docstrings (and equations) of the methods and variables that calculate and record phosphorus runoff.

### Context

Issue(s) closed by this pull request: closes #1566 

- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### Test plan

This change has been tested with the C1F2 pilot farm simulations, resulting in a massive decrease in the recorded amounts of phosphorus runoff. Also, unit tests have been corrected.

### CODE REVIEW

**Review by krb78 — APPROVED** [review]
good eyes on catching this one, Ed 👀

**Comment by PooyaHekmati** [comment]
I'm confused, the chang log says the units of have changed, but I don't see any changes in the units in the code here.

**Comment by krb78** [comment]
true, units in the code haven't changed. We had inadvertently multiplied total kg phosphorus applied by field size, so the output was not kg/ha as the units are intended to be. This fixes that so we are actually reporting the units we claim to be reporting :)

**Review by ew3361zh — APPROVED** [review]
LGTM

**Comment by PooyaHekmati** [comment]
> true, units in the code haven't changed. We had inadvertently multiplied total kg phosphorus applied by field size, so the output was not kg/ha as the units are intended to be. This fixes that so we are actually reporting the units we claim to be reporting :)

Thanks for the explanation, I changed the changelog to: `Corrected recording of phosphorus runoff from top soil layer from kg to kg/ha.`

**Comment by Isgotkowitz** [comment]
> > true, units in the code haven't changed. We had inadvertently multiplied total kg phosphorus applied by field size, so the output was not kg/ha as the units are intended to be. This fixes that so we are actually reporting the units we claim to be reporting :)
> 
> Thanks for the explanation, I changed the changelog to: `Corrected recording of phosphorus runoff from top soil layer from kg to kg/ha.`

Thank you Pooya

**Pull request merged**
