### PR TITLE
Feed emissions updates

### PR DESCRIPTION
**Pull request by jadamchick**
The current feed emissions input file (usable_feeds_emissions.csv) has been a placeholder to get the feed emissions mechanisms up and running. 
This updated file (full_feeds_emissions.csv) has a (nearly) complete set of county_codes and feed emissions factors that can be used for calculating emissions associated with purchased feeds that are fed to cows. 
The metadata files were updated to accommodate the new spreadsheet: file path for purchased_feed_emissions, and feed_emissions_properties to reflect all of the feed ID's that are column headings in the input csv.

### CODE REVIEW

**Review by Isgotkowitz — APPROVED** [review]
LGTM, nice job Julie.

Thank you for making sure to add your metadata properties change to all the other metadata files. There are still some inconsistencies between them though (from unrelated PRs in unrelated sections of the metadata that made it into main). If you don't mind, they could be made entirely consistent by copying and pasting the entire "properties" section from the default metadata into all the others - if not though, pay it no mind. I have a couple open PRs making the same changes, so we would be racing to see who can their PR merged the quickest.

**Review by KFosterReed — APPROVED** [review]
This works as expected and throws an error when a feed not in the dataset is used. I'll think about what the next steps are to enable simulation with feeds that we don't have but also to not let the missing feeds go 'under the radar'

Thanks!

**Comment by jadamchick** [comment]
Thanks @KFosterReed for doing those metadata updates! Unfortunately it is now failing the "Test and Coverage" check, and I don't know where to begin to troubleshoot that. Maybe @Isgotkowitz can help point me in the right direction?

**Comment by Isgotkowitz** [comment]
> Thanks @KFosterReed for doing those metadata updates! Unfortunately it is now failing the "Test and Coverage" check, and I don't know where to begin to troubleshoot that. Maybe @Isgotkowitz can help point me in the right direction?

It was an issue with the pytest version being used in the Action, Pooya put a fix up for it on the main branch. Merging main in should do the trick.

**Pull request merged**
