### PR TITLE
Update Soil Denitrification parameters

### PR DESCRIPTION
**Pull request by KFosterReed**
This is a two line change that fixes:

- [x] A double conversion typo from soil carbon concentration to percent

### Context

Issue(s) closed by this pull request: closes #

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### CODE REVIEW

**Review by Isgotkowitz — APPROVED** [review]
@KFosterReed nice catch. I am approving, the change to denitrification looks good to go. However the test has not been updated, that should be done before this gets merged. Let me know if you would like my help with this.

Also I think the message in the change log could be more specific, like "Removes an incorrect conversion from a fraction to percent when calculating denitrification."

Edit: I have not looked at the results from this change. I am curious, have you taken a look at them? It would be good to double check that they don't have a radical effect on N cycling before this gets merged into the main.

**Comment by KFosterReed** [comment]
> @KFosterReed nice catch. I am approving, the change to denitrification looks good to go. However the test has not been updated, that should be done before this gets merged. Let me know if you would like my help with this.
> 
> Also I think the message in the change log could be more specific, like "Removes an incorrect conversion from a fraction to percent when calculating denitrification."
> 
> Edit: I have not looked at the results from this change. I am curious, have you taken a look at them? It would be good to double check that they don't have a radical effect on N cycling before this gets merged into the main.

Great question! Yes, I actually just did that today and the changes are even more in line with what would be expected: less nitrogen stress on crops due to more N available, more ammonia emissions, more N percolation through layers, N2O emissions much much much closer to expected values.

**Comment by KFosterReed** [comment]
@Isgotkowitz re: test updates. I didn't change anything inside a function and didn't see any failed tests in the logs so I thought that maybe this was a silent bug? If not, I am not sure where / what test needs to be updated so help would be so appreciated!

**Comment by Isgotkowitz** [comment]
> @Isgotkowitz re: test updates. I didn't change anything inside a function and didn't see any failed tests in the logs so I thought that maybe this was a silent bug? If not, I am not sure where / what test needs to be updated so help would be so appreciated!

To run the test suite, you have to run `pytest tests` in the command line - no testing will be run during a regular RuFaS simulation (e.g. running `python main.py`). You can do this locally, or you can check the results in GitHub by clicking on the red X that appears instead of the green check mark.

**Review by matthew7838 — APPROVED** [review]
LGTM along with the test fix.

**Comment by Isgotkowitz** [comment]
Keeping this PR up to date so it will be ready to merge when Kristan gets back from vacation

**Pull request merged**
