### PR TITLE
[Easy][Feed Storage] Add timestamp to Harvested Crop

### PR DESCRIPTION
**Pull request by PooyaHekmati**
The main objective of this PR is to add `harvest_time` and `storage_time` to the `HarvestedCrop` class. It also adds type hints to `config.py` and 'time.py`.

### CODE REVIEW

**Review by ew3361zh — APPROVED** [review]
LGTM!

**Review by KevinP-B — APPROVED** [review]
Type hints added to config.py.

**Review by KevinP-B — APPROVED** [review]
Adds timestamp to Harvested Crop to allow for calculation of storage time.

**Review by KevinP-B — APPROVED** [review]
Time hints added to time.py. Looks good!

**Review by JoeWaddell — APPROVED** [review]
LGTM!

**Pull request merged**
