### PR TITLE
Update pregnancy phos requirements + fix p intake units

### PR DESCRIPTION
**Pull request by KFosterReed**
- Corrects equation for `P_Preg` in `animal_requirements.py`
- Corrects units for `p_intake` from kg to g in `animal_base.py`

### Context

Issue(s) closed by this pull request: closes #

There was an error in the translation of the formula to estimate the phosphorus requirements for pregnancy in the NASEM nutrient requirement methods. This, compounded with a missing unit conversion in the `set_p_intake` function in `animal_base.py` was resulting in unrealistically low phosphorus excretion values. 
- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### Test plan

Tests not yet updated

### CODE REVIEW

**Comment by ltp23** [comment]
Hi Kristan, when you think this is ready to be merged, can you or I remove the print() statements?

**Comment by jadamchick** [comment]
Hi Kristan,
I'm not sure what to make of the results, so just sharing some data here :) I'll shoot you an email with a slightly more extended version. Let me know if you have questions or what else I can do to help diagnose/evaluate. 


<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/jms349/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/jms349/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">


  | Manure P, lact cow g/hd/d | Lac cow P req, g | LAC COW daily DMI per cow, kg/cow   dm | LAC COW daily phosphorus intake   per cow, kg/cow | dietary phosphorus, %
-- | -- | -- | -- | -- | --
10991 q0, original | 30.141 | 54.490 | 28.417 | 0.088 | 0.309
  | 30.028 | 54.481 | 28.345 | 0.088 | 0.310
  |   |   |   |   |  
10991 q0, phos fix branch | 39.513 | 61.510 |   |   |  
  | 39.381 | 61.523 |   |   |  
  | 39.578 | 61.499 | 28.896 | 0.096 | 0.332
  | 39.430 | 61.512 | 28.894 | 0.096 | 0.332
  |   |   |   |   |  
c2f7, original | 21.360 | 35.826 | 20.066 | 0.066 | 0.329
  | 21.300 | 35.424 | 20.132 | 0.066 | 0.329
  |   |   |   |   |  
c2f7, phos fix branch | 32.970 | 40.503 |   |   |  
  | 32.729 | 41.101 | 20.380 | 0.067 | 0.329



</body>

</html>

**Comment by KFosterReed** [comment]
Hey Team! I am going to suggest that pull in this change since this fixes an actual error in the pregnancy requirements and phosphorus unit conversions. I will make an issue about adding a buffer to the phosphorus requirements so that can be a separate PR.

**Review by jadamchick — APPROVED** [review]
Sounds like a plan!

**Pull request closed without merging**
