### PR TITLE
Update feeds labeled as "byproducts" and report quantity fed each day 

### LINKED ISSUE #1187: Create "kg of byproducts fed" report item
**Is your feature request related to a problem? Please describe.**
One output that FARM ES would like reported for the pilot farm is "Total kg (DM) of byproducts fed", according to the list of feeds (attached below) considered as byproducts.  It would be great to be able to automate this calculation as part of RuFaS outputs/report generation. 

**Describe the solution you'd like**
Something along the lines of: 
1. Indicated feeds have some label as "byproducts" 
2. Be able to filter and sum total quantity of "byproduct" feeds fed using report generator 

**Describe alternatives you've considered**
Manually identify which feeds are byproducts + do post hoc math to sum the quantity used. 

**Additional context**
Issue #1181 addresses how feed quantity use is reported, aggregated, and labeled. 

This spreadsheet contains all feeds to be designated as byproducts; currently rations are only utilizing feeds listed in the combined NRC and NASEM feed library. 
The regional byproduct blend is not included on this list, but should be added (ID's 302-305). 

[KB_Copy of User_feeds_byproducts_.xlsx](https://github.com/RuminantFarmSystems/MASM/files/14112699/KB_Copy.of.User_feeds_byproducts_.xlsx)

### PR DESCRIPTION
**Pull request by jadamchick**
This PR addresses issue #1187: a desired output to report for pilot testing farms is the quantity of byproducts fed, according to a list of byproducts supplied by @krb78 (linked to in issue). 

This PR: 
- updates the NASEM_Comp_with_TDN feed csv to align with Kaitlyn's list of feeds to be labeled as byproducts (see questions below)
- adds total_byproducts to be reported by AnimalModuleReporter.report_daily_ration 
- (was done completely by Julie so almost certainly needs refining by a SWE!) 

Report filter: this can be used to see the daily DM fed (/intake) of each feed in the ration (note: it will be more than 365 rows for some feeds if they are fed to more than 1 pen; it will report 1 row per pen fed per day). You can: 1) see the daily total for each feed (& sum it over the last year, manually); then 2) check which of those feeds are labeled as 'by-product/other' in the NASEM_Comp_with_TDN; and 3) verify that the "DMI by feed, daily_byproducts_total" column is equivalent to the sum of the individual byproducts fed. 
```
        {
            "name": "DMI by feed, daily",
            "filters": [
                "AnimalModuleReporter.report_daily_ration.ration_daily_feed_totals.*"
            ],
            "variables": [".*"],
            "slice_start": -365
        }
```

Notes: 

- List of NASEM_Comp_with_TDN feeds labeled as by-product/other that are not on Kaitlyn's list: 3 (apple pomace), 11 (barley malt sprouts), 35 (corn cobs). @krb78 are these okay to also call by-products? 
- Feed 135 - listed as "Poultry byproducts" on NASEM_Comp library but "Potato byproducts" on Kristan's spreadsheet [here](https://docs.google.com/spreadsheets/d/1vOzuEawcU8oFWB2DVWOUNjFuLUDKOuF1/edit#gid=1762147550) @KFosterReed do you have resources we can use to track down which name/number/specs are correct?
-  Many feeds on Kaitlyn's list are in NRC library but not the combined one. Is there another place with the more complete list of feeds that I could/should also update these labels, in case they later get incorporated?

- It reports a warning that there are no feed emissions data for "byproducts_total". Is there a simple way to tell it not to expect or try to report feed emissions data for this? @JoeWaddell 
image

- I am only merging this to the pilot testing branch for now, since the feed libraries are no longer synched up anyway. Once this is completed, will we want to include it on Main as well? I assume yes; are there any complications with changing the Fd_Category labels? (I don't see them used anywhere in RuFaS right now...).

### CODE REVIEW

**Comment by JoeWaddell** [comment]
> It reports a warning that there are no feed emissions data for "byproducts_total". Is there a simple way to tell it not to expect or try to report feed emissions data for this? @JoeWaddell

Sure thing: just made the change locally, so I'll commit to this branch shortly.

> I am only merging this to the pilot testing branch for now, since the feed libraries are no longer synched up anyway. Once this is completed, will we want to include it on Main as well? I assume yes; are there any complications with changing the Fd_Category labels? (I don't see them used anywhere in RuFaS right now...).

With the additional logic to `report_daily_ration`, we'll have to update the NRC library so it also works with this method.

**Comment by krb78** [comment]
Re: >>List of NASEM_Comp_with_TDN feeds labeled as by-product/other that are not on Kaitlyn's list: 3 (apple pomace), 11 (barley malt sprouts), 35 (corn cobs). @krb78 are these okay to also call by-products?

Oops, yes! I feel less certain about corn cobs but it's probably safe to consider it a by-product of corn grain production. So let's go with yes for all of those.

**Review by JoeWaddell — APPROVED** [review]
LGTM (though we'll just need an SWE to check my commit, to ensure it looks good).

**Comment by jadamchick** [comment]
>     * Feed 135 - listed as "Poultry byproducts" on NASEM_Comp library but "Potato byproducts" on Kristan's spreadsheet [here](https://docs.google.com/spreadsheets/d/1vOzuEawcU8oFWB2DVWOUNjFuLUDKOuF1/edit#gid=1762147550) @KFosterReed do you have resources we can use to track down which name/number/specs are correct?
> 

Issue #1228 created to address this mismatch and potentially detect any others

**Review by JoeWaddell — CHANGES_REQUESTED** [review]
Pausing the approval process for the moment, while resolving #1228 and ensuring the NRC comp library will also work with this PR (e.g. adding a `Fd_Category` column to the NRC library).

**Review by JoeWaddell — APPROVED** [review]
Updated and tested using NRC comp library (required changing default_feed options to avoid the NASEM only feed 176).

**Comment by jadamchick** [comment]
Noting that I updated poultry byproduct meal from ID 135 to 137 in NASEM_Comp_with_TDN.csv according to the discussion in Issue 1228 (https://github.com/RuminantFarmSystems/MASM/issues/1228)

**Pull request merged**
