### PR TITLE
Sequential Cropping 

### PR DESCRIPTION
**Pull request by rhensen**
This PR reaches the first version of many of the RUFAS v1 soil and crop objectives:

Management practices:
•	Crop types - corn (grain and silage), alfalfa, grass (tall fescue), soybeans, winter wheat, winter rye, triticale
•	Cover cropping
•	No-till vs. tillage vs. conservation tillage
•	Manure and fertilizer application - surface, incorporation, injections
Outcomes:
•	N2O, NH3, and CO2 Emissions
•	N & P Leaching and Runoff
•	Water use
•	Soil C
•	Crop yields and compositions

Additionally, @brandon and @morrowcj added Sphynx documentation to all attributes and functions within `RUFAS/routines/field/`, except where there is outstanding uncertainty (i.e., GitHub Issues #168, #169, #170, and #174). Any code that remains undocumented will continue to be addressed. 

Major progress has also been made towards unit testing. @brandon has been systematically testing functions in `RUFAS/routines/field/`, starting with the simpler low-level functions (GitHub Issue #184). Many functions remain un-tested (or under-tested), but their progress will continue moving forward. We have already implemented a plan to make more robust tests, with a variety of test cases (using `@pytest.mark.parameterize`). We’ve organized our tests into a nested sub-directory structure within `tests/tests_SoilCrop/`. One notable non-test file within this directory is `mock_classes.py` which contains highly flexible functions for mocking the various classes. This exists as a separate file because the contained functions will be used widely throughout our test files. 

@morrowcj also implemented the major change of refactoring the `BaseCrop` class (`basecrop.py`) and various child classes (`RUFAS/routines/field/crop/crop_types/`: `Alfalfa`, `Corn`, etc.). The old structure had redundancy where the same attribute was set in all the child class files. Now, all common and default attributes are explicitly defined in `BaseCrop` and species-specific attributes are set by the child classes. Default values are now kept in a config file (`crop_config.py`) which contains a dictionary for each accepted crop child class. The child class initialization function assigns crop-specific attributes to the class, read from the config file. This reduces redundancy and allows external tuning of the default crop values without changing the actual files – a requirement for validation in the future. These crop classes can (and should) be further cleaned and refactored to reduce the number of files and redundant code. 
@morrowcj added `config/definitions.py`, which contains a global variable pointing to the root directory of the project. This is/will be useful for validation.

Numerous `# TODO` lines have been added to flag where additional efforts or elaborations are needed. Nearly all of these have been associated with GitHub Issues to address moving forward. 

NOTE: There are lots of changes to the structure of the soil and crop module between the current master and this branch that were originally implemented by Jacob Johnson and Will Donovan that were not merged into Master before their departure. We are still working to understand and improve upon this code.

### CODE REVIEW

**Comment by morrowcj** [comment]
I just pushed a small update, which refactors and tests the crop's nitrogen uptake (`nitrogen_uptake.py` and `nitrogen_fixation.py`).

Some of the integration tests are intentionally failing to remind us to write passing tests in the future (`test_allocate_biomass()`, `test_update_nitrogen()` and `test_fix_nitrogen()`).

I also updated the swat.json files to work with @rhensen's updates to the model.

**Comment by morrowcj** [comment]
I pushed some new tests. Now all tests pass, though there is still an integration test missing (`test_allocate_biomass()`). I've added a `#TODO` and a github issue documenting this.

**Review by KFosterReed — COMMENTED** [review]
Still working on this review but there is something weird going on with the alfalfa planting and harvesting. The input says it is a 'scheduled' harvest_type but it is planting much earlier than the date that is entered as the planting day: 
image

image

I see a 'TODO' in the alfalfa config that is related to the harvest_type but as it is, I can't tell where the decision is being made to plant alfalfa

**Comment by KFosterReed** [comment]
So following up on my previous comment, if you don't have 'optimal' as the harvest type for alfalfa, it will not do multiple cuttings for that crop - which is not what we want. I would be OK with pulling this in if the 'optimal' schedule was actually working as desired but it appears like it is doing some odd combination of optimal and scheduled harvest because it will harvest both at the dates that the model determines to be optimal AND at the scheduled harvest dates so something needs to be fixed here

**Comment by morrowcj** [comment]
I'm going to go ahead and close this PR, since we have moved in a new direction. The functionality contained in this PR will be included in the next major PR from the Crop and Soil team.

**Pull request closed without merging**
