### PR TITLE
Delete old files in save_directory folder

### LINKED ISSUE #1049: Old files in save_directory folder
## Expected Behavior
The save_directory shouldn't have any files on the main branch

## Current Behavior
Files exist in main branch save_directory file

## Possible Solution
Delete the files in the main branch

## Steps to Reproduce
Look at the save_directory folder in the main branch

1.
2.
3.
4.

### PR DESCRIPTION
**Pull request by ktthr**
- Addressed Issue #1049 by deleting all items in save_directory (and the folder itself)
- Linting errors/warnings created: "One of your files includes a space [...]", "The following actions uses node12 [...]", "The 'set-output' command is deprecated [...]"

### CODE REVIEW

**Comment by PooyaHekmati** [comment]
This is a good start @ktthr , 
I don't think we need to keep the save directory, it should be safe to delete and remove the .keep file.
In the remote possibility that someone is still using these files, I think we should make an announcement to the team about this change. Today's whole team meeting can be a good time for it.

**Comment by ktthr** [comment]
@PooyaHekmati Thanks for the feedback! I've just updated the pull request and will bring the topic up at the meeting.

**Comment by PooyaHekmati** [comment]
@ktthr Since the linter is failing, the branch protection doesn't allow you to merge the PR. I am going to force the merge, bypassing the branch protection. Please let me know when you are ready for that.

**Comment by ktthr** [comment]
@PooyaHekmati The PR is ready now-- all commits are pushed to Git. (I'm also ready to address any actions for the merge from my end.)

**Comment by PooyaHekmati** [comment]
Bypassing branch protection as the linter is complaining about the files that are being removed. This PR was announced and discussed in a whole team meeting, no team member is using these files.

**Pull request merged**
