### PR TITLE
Add unpushed changes to docstring

### PR DESCRIPTION
**Pull request by Isgotkowitz**
This PR contains a change to a docstring based on Matthew's comments on #645, which I had written in my remote but didn't push before I merged 645, so this PR adds that missing docstring.

### CODE REVIEW

**Review by michaelRichards99 — APPROVED** [review]
Looks good

**Comment by Isgotkowitz** [comment]
> Looks good

Thanks Michael

**Review by matthew7838 — COMMENTED** [review]
Looks good.

**Review by matthew7838 — APPROVED** [review]
Looks good

**Pull request merged**
