### PR TITLE
Daily Ration & removed hard coded year lengths

### PR DESCRIPTION
**Pull request by militsasotirova**
A ration can now be calculated daily by changing the "formulation_interval" parameter in the json input file to 1.

This seemed to be the simplest way to go about this, especially since we are indexing our days at 1.

### CODE REVIEW

**Comment by militsasotirova** [comment]
Also just committed the code for removing hard coded year lengths.

**Review by wmaxdonovan — COMMENTED** [review]
[ration_report.txt](https://github.com/RuminantFarmSystems/MASM/files/3253346/ration_report.txt)
The update looks good! I pulled it to the most recent version of the branch Jacob and I are working on and it ran with the barnyard dataset which runs for 7 years and covers a leap year. This was the ration report output. I don't know what it is supposed to look like, but if this is looking good to you, it is compatible with the leap year updates.

**Comment by militsasotirova** [comment]
Sounds good! The master branch has the code to output ration to a csv file, but this looks good for now. Thank you so much!

**Comment by KFosterReed** [comment]
This looks good to me!

**Review by KFosterReed — APPROVED** [review]

**Review by wmaxdonovan — APPROVED** [review]
Meant to approve this commit. Just saw I only commented.

**Review by manfei-L — APPROVED** [review]

**Pull request merged**
