### PR TITLE
Updating ration.py

### PR DESCRIPTION
**Pull request by militsasotirova**
Ration is up to date in terms of pseudocode and there is a new json file and feed library with which to test this code- testing_ration_feed.json and testing_ration_feedlib.csv.

### CODE REVIEW

**Review by ombenomr — APPROVED** [review]

**Review by ombenomr — APPROVED** [review]

**Review by KFosterReed — APPROVED** [review]
This also looks good. I love the references to the Pseudocode equation numbers

**Review by ombenomr — APPROVED** [review]

**Review by ombenomr — APPROVED** [review]

**Review by ombenomr — COMMENTED** [review]
In function "test_ration" try to read the input from json file.

**Review by ombenomr — COMMENTED** [review]
In function "test_ration" try to read the input from json file.

**Review by ombenomr — APPROVED** [review]

**Comment by militsasotirova** [comment]
Sorry, I re-opened the pull request because there are some unmerged commits that I'm trying to figure out.

**Pull request merged**
