### PR TITLE
IM validate array elements

### PR DESCRIPTION
**Pull request by ew3361zh**
PR to validate array elements of any type.

### CODE REVIEW

**Comment by ew3361zh** [comment]
Two main issues with solution as currently written:

1. The potential solution for validating an array of objects works but it essentially creates two parallel tracks within the validate_element() function to accommodate the structure of an array of objects which is contributing to _validate_data() now violating the complexity Codefactor limit.

I am working on trying to reduce the complexity but any suggestions are welcome.

2. The current solution does not work to validate a simple array of primitive types.

I see several possible ways forward for the latter issue of not being able to validate primitive types:
-Making all arrays be arrays of objects.
-Continuing as we had it before where we’re not validating the elements of arrays of primitive types but are validating elements of arrays of objects.
-Continuing to look for solution that will work with both types of arrays. If this is the preferred solution, I would want to have a meeting to discuss possible avenues forward.

**Comment by ew3361zh** [comment]
Being taken care of elsewhere.

**Comment by PooyaHekmati** [comment]
> Being taken care of elsewhere.

Where?

**Comment by ew3361zh** [comment]
> > Being taken care of elsewhere.
> 
> Where?

It sounded like from the ATM that @ltp23 was working on it. We have an issue for this #683 which I thought would be a more appropriate place to note progress and next steps on addressing it.

**Comment by PooyaHekmati** [comment]
> > > Being taken care of elsewhere.
> > 
> > 
> > Where?
> 
> It sounded like from the ATM that @ltp23 was working on it. We have an issue for this #683 which I thought would be a more appropriate place to note progress and next steps on addressing it.

I think it is better to keep the branch and let @ltp23 decide if he wants to use the work that is here or not.

**Comment by Isgotkowitz** [comment]
@ew3361zh can this PR be closed?

**Comment by ew3361zh** [comment]
> @ew3361zh can this PR be closed?

I think so. We've surpassed the need for it as a reference. This is being handled by #1345.

**Pull request closed without merging**
