### PR TITLE
Adding pen animal combination to manure daily output data

### PR DESCRIPTION
**Pull request by ltp23**
Issue #1138 

This PR adds the animal combination associated with each pen to the manure output data.

Example CSV filter file

```
ManureHandlerDailyOutput_Pen_.*_CALF.housing_methane
ManureHandlerDailyOutput_Pen_.*_CALF.housing_carbon_dioxide
ManureHandlerDailyOutput_Pen_.*_CALF.housing_ammonia

ManureHandlerDailyOutput_Pen_.*_GROWING.housing_methane
ManureHandlerDailyOutput_Pen_.*_GROWING.housing_carbon_dioxide
ManureHandlerDailyOutput_Pen_.*_GROWING.housing_ammonia

ManureHandlerDailyOutput_Pen_.*_CLOSE_UP.housing_methane
ManureHandlerDailyOutput_Pen_.*_CLOSE_UP.housing_carbon_dioxide
ManureHandlerDailyOutput_Pen_.*_CLOSE_UP.housing_ammonia

ManureHandlerDailyOutput_Pen_.*_LAC_COW.housing_methane
ManureHandlerDailyOutput_Pen_.*_LAC_COW.housing_carbon_dioxide
ManureHandlerDailyOutput_Pen_.*_LAC_COW.housing_ammonia

ManureTreatmentDailyOutput_Pen_.*_CALF.storage_methane
ManureTreatmentDailyOutput_Pen_.*_CALF.storage_ammonia
ManureTreatmentDailyOutput_Pen_.*_CALF.storage_nitrous_oxide

ManureTreatmentDailyOutput_Pen_.*_GROWING.storage_methane
ManureTreatmentDailyOutput_Pen_.*_GROWING.storage_ammonia
ManureTreatmentDailyOutput_Pen_.*_GROWING.storage_nitrous_oxide

ManureTreatmentDailyOutput_Pen_.*_CLOSE_UP.storage_methane
ManureTreatmentDailyOutput_Pen_.*_CLOSE_UP.storage_ammonia
ManureTreatmentDailyOutput_Pen_.*_CLOSE_UP.storage_nitrous_oxide

ManureTreatmentDailyOutput_Pen_.*_LAC_COW.storage_methane
ManureTreatmentDailyOutput_Pen_.*_LAC_COW.storage_ammonia
ManureTreatmentDailyOutput_Pen_.*_LAC_COW.storage_nitrous_oxide
```

### CODE REVIEW

**Review by jadamchick — APPROVED** [review]
Thanks Loi, this looks great! Including the example filter file was very helpful. 
When I used the filters to generate a report, they worked as expected and the values match up with what's expected from using earlier methods.

**Review by tomhuhh — APPROVED** [review]
Thanks @ltp23 ~ This works great for me. 

My question-  does this mean that the code in the report json filter file will need to be updated once this is merged into main? I think this question is more for @jadamchick 

Thanks!

**Comment by jadamchick** [comment]
> Thanks @ltp23 ~ This works great for me.
> 
> My question- does this mean that the code in the report json filter file will need to be updated once this is merged into main? I think this question is more for @jadamchick
> 
> Thanks!

Yep! there are a number of improvements to the filter that can be made after the PR's being worked on this week -- which is part of why I have not yet added it to the main branch. Coming soon! Loi's example filters are super useful for playing with in the mean time.

**Comment by ltp23** [comment]
Thanks everyone!

**Pull request merged**
