### PR TITLE
Dm manure

### LINKED ISSUE #61: Transplant manure code closer to manure
No more development on dj_manure. Move manure storage and management code to dm_manure.

### LINKED ISSUE #63: Link manure storage with manure excretion
Lay groundwork for complete animal to crop/soil connection via manure storage and management

### PR DESCRIPTION
**Pull request by wmaxdonovan**
Dm manure is the base manure module implemented to link manure excretion in the animal module with field management in the fields module. This should not be confused with ym_manure which is the implementation of Varma's new table. ym_manure is an extension and specification of the structures implemented in dm_manure. After the lifecycle cleanup, this appears to be working correctly on runs of the 4 json files (barnyard, animal_management, LT, and ARL). The primary behaviors implemented are 

1. The creation of objects for manure handling, separation, and storage in manure_storage/manure_storage.py based on information provided for each pen in the animal management json (user specification is updated in ym_manure).
2. The linkage and processing of excreted manure nutrients passed from the animal module to the manure module implemented in the animal manure excretion submodule and manure_storage/manure_storage.py
3. The formulation of manure applications based on user requested nutrients and manure available in storage implemented in field_management/manure_application.py. In the case that there is insufficient manure in storage, manure is "purchased" with nutrient value presets taken from Peter Vadas' 2009 SurPhos (these presets for phosphorus and nitrogen content can be found in field_management/manure_application.py.
4. The implementation of phosphorus excretion in the animal module.

The majority of this work was implemented a few months ago in the earliest commits listed. The remaining commits constitute the implementation of phosphorus excretion and various merges / cleanups from other branches.

closes #63 
closes #61

### CODE REVIEW

**Comment by KFosterReed** [comment]
So I just tried to run dm_manure with the animal_management.json and I got this error: 
Simulating \Traceback (most recent call last):
  File "C:/Users/kfr3/PycharmProjects/MASM/main.py", line 45, in <module>
    main()
  File "C:/Users/kfr3/PycharmProjects/MASM/main.py", line 38, in main
    RUFAS.simulate(input_file_path)
  File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\simulation_engine.py", line 62, in simulate
    annual_simulation()
  File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\simulation_engine.py", line 114, in annual_simulation
    daily_simulation()
  File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\simulation_engine.py", line 84, in daily_simulation
    routines.daily_animal_routine(state.animal_management, state.feed, weather, time)
  File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\routines\animal\animal_management.py", line 40, in daily_animal_routine
    animal_management.daily_updates(feed, weather, time)
  File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\routines\animal\animal_management.py", line 654, in daily_updates
    self.heiferIIIs, self.cows)
  File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\routines\animal\life_cycle\life_cycle.py", line 369, in daily_update
    cow_stage = heiferIII.update(date)
  File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\routines\animal\life_cycle\heiferIII.py", line 118, in update
    c.MATURE_BODY_WEIGHT_REGULAR)
AttributeError: module 'RUFAS.routines.animal.life_cycle.animal_events_constants' has no attribute 'MATURE_BODY_WEIGHT_REGULAR'


It looks like there is no event 'MATURE_BODY_WEIGHT_REGULAR' in the master branch. Is it possible that master needs to be pulled into dm_manure again? @katrina433 what do you think?

**Comment by KFosterReed** [comment]
Ok, I'm not 100% sure what happened but it looks like this commit from Katrina:  540125f has the right version of heiferIII.py but then the next commit from Max:f77ebca has the wrong version... can we undo the changes from that commit only?

**Comment by wmaxdonovan** [comment]
> Ok, I'm not 100% sure what happened but it looks like this commit from Katrina: [540125f](https://github.com/RuminantFarmSystems/MASM/commit/540125f02d074f5ed8f0e15b0517d20520208759) has the right version of heiferIII.py but then the next commit from Max:f77ebca has the wrong version... can we undo the changes from that commit only?

Hey @KFosterReed – sorry I'm just getting to this, but you may need to pull the most recent version of dm_manure. The last commit I made before opening the pull request (c1d2baf) was to address this issue, and unless I'm missing something, the most up to date version is working correctly. Is there a separate issue with heiferIII?

**Comment by wmaxdonovan** [comment]
Saved the current state and message for this pull request. Joseph is implementing a few more equations and I am cleaning up the pull request to reopen in the next week.

**Pull request closed without merging**
