### PR TITLE
Adding Updated emissions files with new data

### PR DESCRIPTION
**Pull request by KFosterReed**
The new feed emissions files have updated values for the total feed emissions in the `full_feeds_emissions_July2024.csv` and the actual estimates for the land use change emissions in the `full_feeds_land_use_change_emissions_July2024.csv` file. 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What
To test these new files, run a simulation with animals and evaluate the values reported by the purchased feed emissions outputs

### Why
Previously the land use change emissions factors were just duplicates of the total purchased feed emissions. The new land use change emissions file provides real estimates for the emissions associated with land use change of feeds. Total emissions estimates are also based on updated methods and data.

### CODE REVIEW

**Comment by KFosterReed** [comment]
Note that before moving from draft I will delete the old LUC emissions file and update the metadata to reference the new files

**Comment by krb78** [comment]
finally did this and it appears to work great! I tested c2f7 and c2f14. the LUC emissions were ~10% of the total emissions in each. some feeds didn't have LUC, but that's fine :) and all the addition and subtraction checked out!

**Review by PooyaHekmati — APPROVED** [review]
[LGTM](https://lgtm.lol/i/438)

**Review by Fjordrunner — APPROVED** [review]
Only comment I would say is that including "new" after "July2024" in the names of the .csv files is slightly redundant. Really nitpicky tho and in general this LGTM!

**Pull request merged**
