### PR TITLE
[Animal] Fixing bug in `ReproStateManager` when pregnant cow enters herd during simulation initialization.

### LINKED ISSUE #1463: Errors occur when new animal population files are created.
We are not able to create a new animal population file directly from initializing a new herd for two reasons:

1. The animal population metadata properties are out of date
2. Once the meta data properties are fixed, then there are occasional runtime errors related to either the ReproStateEnum or the body_weight_history.

## Expected Behavior
We should be able to save the initialized herd population file as described in the RuFaS Command Line Arguments and then use that saved population file as the input to initialize a new herd

## Current Behavior

There are two barriers to this success: 

1. The metadata properties for the repro programs need to be updated
2. There are occasional errors that arise that stop the simulation. These two errors are in the attached files:

[c2f9_jersey_errors_27-Mar-2024_Wed_12-03-59.json](https://github.com/RuminantFarmSystems/MASM/files/14782111/c2f9_jersey_errors_27-Mar-2024_Wed_12-03-59.json)
[c2f9_jersey3_errors_27-Mar-2024_Wed_13-48-29.json](https://github.com/RuminantFarmSystems/MASM/files/14782112/c2f9_jersey3_errors_27-Mar-2024_Wed_13-48-29.json)

## Steps to Reproduce

To replicate the first metadata error
1. Run a simulation and save the animals (--save_animals) and specify a directory that you can use as an input file (--save_animals_dir)
2. Reference that filepath in the animal_population filed in the metadata file

To replicate the second, runtime error
4. On the JerseHerd_hotfix_pilot_testing_Dec2023 branch, run the c2f28_metadata or c2f9_metadata files

## Context (Environment)
This is preventing us from running farms that have Jersey breed animals which is critical for our success in the FARM ES collaboration

I believe there were some changes made in the repro refactor that changed some of the repro metadata inputs and potentially the animal reproduction attributes that are related to this. 

## Detailed Description
When an animal population file is saved, the animals in that population should be able to initialize a new simulation without manually modifying the metadata or the population file.

### LINKED ISSUE #1539: Cows entering preg check with ReproStateEnum other than PREGNANT - throws error and ends simulation if tries to exit state
## Expected Behavior

I think that cows entering preg check should have the ReproStateEnum of PREGNANT. Then, if self._compare_randomized_rate_less_than("loss_rate"), she loses the pregnancy and the ReproStateEnum exits the pregnant state. 

## Current Behavior

Sporadically, a simulation will end early with the error: 'Attempting to exit a state that is not entered: ReproStateEnum.PREGNANT' and reference to line 1622 in cow.py (full error message attached below). This seems to happen more often in herds with a higher rate of preg loss (which makes sense). 

What I think is happening: occasionally a cow enters this loop with ReproStateEnum.WAITING_FULL_ED_CYCLE. If the dice decide that she is to "lose her pregnancy", it throws the error when trying to exit pregnant state. 

[c1f1_monensin_1of4_11Apr_warnings_11-Apr-2024_Thu_14-53-42.json](https://github.com/RuminantFarmSystems/MASM/files/14950905/c1f1_monensin_1of4_11Apr_warnings_11-Apr-2024_Thu_14-53-42.json)

How I got there: 
a) insert this print statement: print(self._repro_state_manager._states) on line 1622. As soon as a cow comes through with the "waiting for full estrus cycle" state, the simulation ends. 

image

b) insert the same print statement on line 1621. Occasionally a cow will show up with the "waiting for full estrus cycle" state but the simulation does not end (presumably because she keeps her pregnancy and it never tries to exit the Pregnant state). 
image
image

## Possible Solution

I'm not sure, I haven't investigated why cows with ReproStateEnum.WAITING_FULL_ED_CYCLE are entering _handle_preg_check

## Steps to Reproduce

1. Enter one of the print statements into cow.py as described above 
2. To see it more frequently, increase preg_loss_rate_1 (or 2 or 3, or all of the above) to 0.1. 
3.
4.

## Context (Environment)

Because this error happens sporadically and causes the simulation to end and not continue on to later simulations in the scenario manager list, it is very disruptive of work flow. 
When trying to run a herd with intentionally increased preg loss rates, I had to run it ~25 times (manually restarting every time) to get 4 complete simulations. 

I do not know the implications for herd or results of having individual cows with inappropriate repro state / preg check mismatch.

### PR DESCRIPTION
**Pull request by Isgotkowitz**
The PR ensures that a Cow's state of pregnancy is initialized correctly for new cows.

### Context

Issue(s) closed by this pull request: closes #1463, closes #1539 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

When a Cow is initialized, it is checked whether or not it is pregnant. If so, then the `ReproStateManager` is entered into the `PREGNANT` state.

### Why

When a simulation is already running, a cow is created when a HeiferIII births a calf - so newly created cows aren't pregnant. But on the first day of a simulation, cows are pulled from the animal population and put into the herd. Some of those cows may be pregnant, and this case needs to handled.

### Test plan

This branch was merged into `pilot_testing_Dec2023`, and the C1F1 pilot testing scenario was successfully run 10 times with `preg_loss_rate_1` bumped up to 0.1

A unit test has been added for a `Cow`'s `init` method. It is not comprehensive, but I think it is sufficient for testing added functionality.

### Open Questions
Are there other conditions that a cow should be checked for when initialized?

### CODE REVIEW

**Review by jadamchick — APPROVED** [review]
Runs well for me! I merged this into one of my branches with a herd that threw this error ~3/4 runs previously. It ran 4 times consecutively and did not print any cows entering the preg check loop with a ReproStateEnum of anything other than Pregnant.

**Comment by jadamchick** [comment]
ps - reminder to update the changelog :)

**Comment by Isgotkowitz** [comment]
> Runs well for me! I merged this into one of my branches with a herd that threw this error ~3/4 runs previously. It ran 4 times consecutively and did not print any cows entering the preg check loop with a ReproStateEnum of anything other than Pregnant.

Awesome. Do you think there is are a list of invalid combinations of `ReproStateEnum` elements that could/should be enumerated and checked for? I had this discussion with @Rebecavb yesterday and it seems there are some combinations which should be allowed, and some that shouldn't.

**Comment by jadamchick** [comment]
> > Runs well for me! I merged this into one of my branches with a herd that threw this error ~3/4 runs previously. It ran 4 times consecutively and did not print any cows entering the preg check loop with a ReproStateEnum of anything other than Pregnant.
> 
> Awesome. Do you think there is are a list of invalid combinations of `ReproStateEnum` elements that could/should be enumerated and checked for? I had this discussion with @Rebecavb yesterday and it seems there are some combinations which should be allowed, and some that shouldn't.

Maybe? I don't think I have a complete enough handle on how these elements are used to think through invalid combo's. Happy to discuss it though if you/others think it's a good idea.

**Comment by Isgotkowitz** [comment]
> > > Runs well for me! I merged this into one of my branches with a herd that threw this error ~3/4 runs previously. It ran 4 times consecutively and did not print any cows entering the preg check loop with a ReproStateEnum of anything other than Pregnant.
> > 
> > 
> > Awesome. Do you think there is are a list of invalid combinations of `ReproStateEnum` elements that could/should be enumerated and checked for? I had this discussion with @Rebecavb yesterday and it seems there are some combinations which should be allowed, and some that shouldn't.
> 
> Maybe? I don't think I have a complete enough handle on how these elements are used to think through invalid combo's. Happy to discuss it though if you/others think it's a good idea.

I think it is ok to leave for now as it seems to be functioning correctly. But would like to get @ltp23's opinion too.

**Comment by ltp23** [comment]
Good fix, Ed! I was able to reproduce the errors for the farm c1f1 and this fix did prevent them. 

One thing I'm still pondering is if we should re-evaluate the `do_not_breed` flag (like in the `_check_do_not_breed_flag` method) when a cow is pregnant at the point of instantiation. Currently, the pregnancy check happens only when the cow is in the breeding phase (line 869).

When I ran the simulation on the farm c1f1, with the updates, I got the following animal counts. The lactating and dry cow numbers look normal to me, but heiferI and heiferII counts dropped off quite a bit, and as a consequence, the total number of animals did as well. I think there may be something going on with those two groups. 

c1f1_animal-counts-16-Apr-2024_Tue_12-39-19

**Review by ltp23 — APPROVED** [review]

**Comment by Isgotkowitz** [comment]
> Good fix, Ed! I was able to reproduce the errors for the farm c1f1 and this fix did prevent them.
> 
> One thing I'm still pondering is if we should re-evaluate the `do_not_breed` flag (like in the `_check_do_not_breed_flag` method) when a cow is pregnant at the point of instantiation. Currently, the pregnancy check happens only when the cow is in the breeding phase (line 869).
> 
> When I ran the simulation on the farm c1f1, with the updates, I got the following animal counts. The lactating and dry cow numbers look normal to me, but heiferI and heiferII counts dropped off quite a bit, and as a consequence, the total number of animals did as well. I think there may be something going on with those two groups.
> 
> c1f1_animal-counts-16-Apr-2024_Tue_12-39-19

Thanks Loi. I can't speak to what is going on with the heiferIs and IIs, but this is something that I think @jadamchick and @krb78 should take a look at.

I don't fully understand how the `do_not_breed` flag is used, but I think you're right about it needing to be revisited. It appears to be created on the fly in the `_check_do_not_breed_flag` method - but it seems like a variable that ought to be declared and documented in the init method.

**Comment by jadamchick** [comment]
Hi, thanks for noting this about the animal counts dropping off at the beginning of the simulation. I'm guessing that it was just a case of the initial inputs for the calf + heifer numbers on this particular herd being higher than what the herd reaches for steady state (though can't say 100% without running it both before + after this update is made to compare/rule out something caused by this change).

**Comment by jadamchick** [comment]
> Good fix, Ed! I was able to reproduce the errors for the farm c1f1 and this fix did prevent them.
> 
> One thing I'm still pondering is if we should re-evaluate the `do_not_breed` flag (like in the `_check_do_not_breed_flag` method) when a cow is pregnant at the point of instantiation. Currently, the pregnancy check happens only when the cow is in the breeding phase (line 869).
> 
> When I ran the simulation on the farm c1f1, with the updates, I got the following animal counts. The lactating and dry cow numbers look normal to me, but heiferI and heiferII counts dropped off quite a bit, and as a consequence, the total number of animals did as well. I think there may be something going on with those two groups.
> 
> c1f1_animal-counts-16-Apr-2024_Tue_12-39-19

I suspected that this dropping off was because the initial inputs for calf + heifer numbers are higher than necessary for this herd. I tried changing the initial inputs to be close to the final values for each animal population, and the graph looks quite a bit more stable: 
image

**Pull request merged**
