### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by PooyaHekmati**
Add priority level definitions to the readme.

### CODE REVIEW

**Review by JoeWaddell — APPROVED** [review]
My immediate enthusiastic approval of this PR is in no way related to the fact that I'm currently re-reading the Once and Future King for about the tenth time. Also not related to "Priority One" messages being a thing in Star Trek.

On a more serious note: are we considering these levels as roughly exponential? As in the jump from P0 from P1 is a bigger step than P2 to P1? 

Also: should we have a name like this for for non-priority tasks, so that people get in the habit of labeling things every time they open an issue/PR? Just thinking about Issues or Project tasks that aren't _yet_ a priority, but may be a Future Priority, or even a Non-Priority task, though I can see the argument that those are still priorities, just low-ranked.

**Review by KFosterReed — APPROVED** [review]
I regret taking so long to read these!

**Comment by KFosterReed** [comment]
I also like Joe's suggestion for a future priority category as well :)

**Comment by PooyaHekmati** [comment]
> On a more serious note: are we considering these levels as roughly exponential? As in the jump from P0 from P1 is a bigger step than P2 to P1?

It should be that way, but it usually isn't :D 

> Also: should we have a name like this for for non-priority tasks, so that people get in the habit of labeling things every time they open an issue/PR? Just thinking about Issues or Project tasks that aren't _yet_ a priority, but may be a Future Priority, or even a Non-Priority task, though I can see the argument that those are still priorities, just low-ranked.

Let's chat about this so I can have a better understanding of what you are thinking about. If my current understanding of your comment is correct, a typical labeling system would be: 

1. wish
2. low
3. mid
4. high
5. UBN (unbreak now!)

**Comment by JoeWaddell** [comment]
> It should be that way, but it usually isn't :D

I'll be sure to remind folks in the Animal Module that when we get the real fire-breathing dragon tasks, that we need to drop what we're doing (unless it's slaying a different dragon) to help out. I've worked in a lab before where *everything* was labeled as a critical task, which means that *nothing* was treated a critical task - it became a challenge to sort out what's *actually* important. I think keeping that P0 in reserve for when it's really needed is a good choice.

> Let's chat about this so I can have a better understanding of what you are thinking about. If my current understanding of your comment is correct, a typical labeling system would be:
> 
>     1. wish
> 
>     2. low
> 
>     3. mid
> 
>     4. high
> 
>     5. UBN (unbreak now!)

We can definitely chat about this, but to put my thoughts into words: I think what you've merged to master is great. Instead of adding two more levels, I'd just think about adding a wish/future label. That way we retain the minimalist nuance of low/high priority for P1 and P2, and we reserve P0 for the critically time-sensitive tasks.

**Pull request merged**
