### PR TITLE
updated OM save_xyz func names to dump_xyz across model

### PR DESCRIPTION
**Pull request by ew3361zh**
This PR seeks to address issue #521 to update the names of all the OM save_xyz functions to dump_xyz which more accurately reflects what they do.

Changes were made in OutputManager.py, test_misc.py, test_user_prompt.py, and main.py.

Doc strings were also updated from save -> dump.

A search across files for "save_" after these changes were made yielded no further references to the save_xyz OM functions.

Tested by running a simulation as well as running the test suite and did not find any issues.

### CODE REVIEW

**Review by PooyaHekmati — CHANGES_REQUESTED** [review]
Nice work.
I think the issue and the title of this PR are specifically asking to change the functions that have save_ prefix in their names. This doesn't apply to _dict_to_file_json and _list_to_file_txt.

**Comment by ew3361zh** [comment]
> Nice work. I think the issue and the title of this PR are specifically asking to change the functions that have save_ prefix in their names. This doesn't apply to _dict_to_file_json and _list_to_file_txt.

Makes sense, I returned the docstrings on those functions back to their original state.

**Review by PooyaHekmati — APPROVED** [review]
LGTM

**Review by JoeWaddell — APPROVED** [review]
Looks good!

**Pull request merged**
