### PR TITLE
Updated Dynamic BASE_BRANCH Fetch to GH Actions

### LINKED ISSUE #832: `set-output` command in GitHub linting action dependency is being deprecated
GitHub Actions is deprecating the `set-output` command ([read this](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)), which is used in the linting action workflow. The dependency is [get-changed-files](https://github.com/jitterbit/get-changed-files) by jitterbit.

## Expected Behavior

The GitHub linting action should run without error.

## Current Behavior

The GitHub linting action runs fine, but produces errors.

## Possible Solution

For jitterbit's implementation, then make the changes and maintain it internally. This may be extremely easy, because someone has already done this in a [PR](https://github.com/jitterbit/get-changed-files/pull/70).

## Steps to Reproduce

1. Click on the linting "Details" button from any linting run, and expand the "Setting up dependency for getting changed files".
2. Scroll down and you will see the warnings.
3.
4.

### LINKED ISSUE #1453: [GH Actions] Fix the warnings related to nodejs and `set-output` command when running actions
## Urgency Level

- [ ] Urgent: a critical feature or fix is needed
- [ ] High: the issue significantly impacts the user experience
- [ ] Medium: the issue affects functionality but has a workaround
- [x] Low: the issue doesn't have a significant immediate impact
- [ ] Wishful: the issue should not be prioritized over any others
- [ ] Unsure: the urgency level has not been or cannot be assessed at this time 

## Status

When running github actions, I see the following warnings. 

image

## Intention

The actions are still running okay but we probably want to update the versions of things before they get deprecated. 

## Request

- [ ] Fix nodejs-related warnings.
- [ ] Fix `set-output` deprecation warnings.
- [ ] Update all the yaml files that we currently have.

### LINKED ISSUE #1657: Add `default_task.json` to .gitignore and the list of protected files
After #1648 is merged, there will be a `default_task.json` input that will run the default scenario.

## Status

`default_task.json` is a normal file, that can be changed through a PR like any other input file.

## Intention

Protect the `default_task.json` file so that it will not be changed accidentally through a pull request.

## Request

Add the following path to the gitignore file: `input/data/tasks/default_task.json`.
Modify the GitHub Actions workflow `combined_format_lint_test_mypy.yml` so that it will fail if `default_task.json` is modified.

### PR DESCRIPTION
**Pull request by ew3361zh**
Redoes code from PR #1686

### Context

Issue(s) closed by this pull request: closes #1453 closes #1657 closes #832

- [N/A] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

See #1686 for full details. The big difference between this PR and that is in the updated fetch for the base branch to compare for getting changed files, this will dynamically search for the base branch but fallback to main if it doesn't find another branch. This will prevent the issue of how it failed looking for the base branch when it was merged into main previuosly.

### Why

See #1686

### How

See #1686

### Test plan

To test that this new dynamic search for the base branch would work when merged into main:

1. Created a new branch `test-main` off `main`.
2. Updated the GH action workflow to make `test-main` the on push and on pull_request branch:
```
on:
  push:
    branches: [ test-main ]
  pull_request:
    branches: [ test-main ]
```
3. Updated the `Get all added or modified files` step to reflect this new base branch as well:
```
- name: Get all added or modified files
        run: |
          BASE_BRANCH=${{ github.base_ref }} || "test-main"
          git fetch origin $BASE_BRANCH
          if ! git rev-parse --verify --quiet origin/$BASE_BRANCH; then
            echo "Fallback to test-main branch because $BASE_BRANCH does not exist."
            BASE_BRANCH="test-main"
            git fetch origin $BASE_BRANCH
          fi
```
4. Pushed that branch to GH.
5. Created a branch off `test-main` (`test-test-main`) and made some changes and pushed those to github.
6. Merged `test-test-main` into `test-main` with the above-altered GH action.
7. Result was it couldn't find the base branch as expected but successfully fell back to `test-main` branch and all GH actions proceeded as expected.
Screenshot 2024-05-22 at 5 35 07 PM

### CODE REVIEW

**Review by Isgotkowitz — APPROVED** [review]
Nice job identifying the issue and coming up with a fix Niko.

Only comment is that #1657 also calls for the default task to be added to the .gitignore. This PR is small enough that I think it would be ok to add that in as well - and then the issue can be closed out with nothing remaining to do for it.

**Comment by ew3361zh** [comment]
> Nice job identifying the issue and coming up with a fix Niko.
> 
> Only comment is that #1657 also calls for the default task to be added to the .gitignore. This PR is small enough that I think it would be ok to add that in as well - and then the issue can be closed out with nothing remaining to do for it.

@Isgotkowitz I added it to the .gitignore file but nothing happened which reminded me of why we created that GH protected paths action in the first place - essentially, if something is already tracked by GH adding it to the .gitignore doesn't do anything. Ignore in the GH sense means you don't want GH to track it at all so you have to tell git to remove it from the tracked files which then removes it from GH altogether (which we don't want).

**Comment by Isgotkowitz** [comment]
> > Nice job identifying the issue and coming up with a fix Niko.
> > Only comment is that #1657 also calls for the default task to be added to the .gitignore. This PR is small enough that I think it would be ok to add that in as well - and then the issue can be closed out with nothing remaining to do for it.
> 
> @Isgotkowitz I added it to the .gitignore file but nothing happened which reminded me of why we created that GH protected paths action in the first place - essentially, if something is already tracked by GH adding it to the .gitignore doesn't do anything. Ignore in the GH sense means you don't want GH to track it at all so you have to tell git to remove it from the tracked files which then removes it from GH altogether (which we don't want).

True, I had forgotten how we ran into that issue before. In that case, I guess it doesn't really matter if its in the gitignore or not. Either way, #1647 can be closed.

**Review by allisterakun — APPROVED** [review]
LGTM!

**Pull request merged**
