### PR TITLE
Daily_milk_fix

### PR DESCRIPTION
**Pull request by JoeWaddell**
Quick fix for problem outlined in Issue #918.

Simple rearrangement of order of operations, and addition of argument to disallow negative milk production values.

### CODE REVIEW

**Review by tomhuhh — APPROVED** [review]
The algorithm makes sense to me, and the code runs without crash. I would like to mention that even when I set the 'cull_milk_production' value to be 0, the minimum milk production for lactating cows after a 4-year simulation is still above 0, which is about 14.6 kg with the default_animal.json.

**Comment by tomhuhh** [comment]
Thanks @JoeWaddell! Good work! I think it would be beneficial if Julie would like to review this PR as well. Thanks!

**Review by jadamchick — APPROVED** [review]
Looks good to me! 
I did the following to confirm: 
1. Ran the default input json's on the main branch, with the following changes: added a 0 to all herd demographic numbers (10x size the herd), set cull_milk_production to 0, and ran the simulation for 7 years with set_seed to False.  --> Resulted in 57 animal-days with negative milk, all lactating animals, parity 2-4, 900+ DIM
2. Ran the daily_milk_fix branch with those same inputs/changes: no negative milk 
3. Ran my private branch I was using for Zoetis playing around where I have funky settings (including cull milk production = 4 and DNB_time = 1000) and originally found the negative milk. Running 267 animals over 7 years, I got 347 negative milk-days, all dry cows, all parity=1. 
4. Merged daily_milk_fix into my private branch and ran with no other changes: no negative milk. 

Thanks for giving me the chance to review.

**Review by YijingGong — APPROVED** [review]
Works perfectly for this purpose. I set "cull_milk_production" to 0 and changed"do_not_breed_time" to 100 to make more cows not pregnant and produce less and less milk and ran for 7 years. I saw thousands of 0 estimated_daily_milk_produced in my output csv for the 'Cow.milking_update.milk_data_at_milk_update.lactating = TRUE' cows.

**Review by Isgotkowitz — APPROVED** [review]
Looks good, love seeing bounds being placed on attributes.
Two things that came to mind when looking at this:
1. If there is a test for this method, it would be good to make sure that there is at least one case that tests estimated daily milk production being negative. Given the changes made though I am sure it would pass with flying colors.
2. Is it routine/expected for `estimated_daily_milk_produced` to be negative, or would that indicate a bug somewhere? If the latter, it may be good to raise a warning to the OutputManager indicating that this is occuring.

**Comment by JoeWaddell** [comment]
Thanks for the quick review @Isgotkowitz! 

> * If there is a test for this method, it would be good to make sure that there is at least one case that tests estimated daily milk production being negative. Given the changes made though I am sure it would pass with flying colors.

Unfortunately we still lack test coverage in a lot of this part of the model: so it'll be one of the many tasks of the new undergrad programmers when they get started on reducing this kind of tech debt!

> * Is it routine/expected for `estimated_daily_milk_produced` to be negative, or would that indicate a bug somewhere? If the latter, it may be good to raise a warning to the OutputManager indicating that this is occuring.

Not routine, but an edge case of how milk variation is handled. This fix should squash that problem, since this is where the negative values were being introduced.

**Comment by Isgotkowitz** [comment]
> Thanks for the quick review @Isgotkowitz!
> 
> > * If there is a test for this method, it would be good to make sure that there is at least one case that tests estimated daily milk production being negative. Given the changes made though I am sure it would pass with flying colors.
> 
> Unfortunately we still lack test coverage in a lot of this part of the model: so it'll be one of the many tasks of the new undergrad programmers when they get started on reducing this kind of tech debt!
> 
> > * Is it routine/expected for `estimated_daily_milk_produced` to be negative, or would that indicate a bug somewhere? If the latter, it may be good to raise a warning to the OutputManager indicating that this is occuring.
> 
> Not routine, but an edge case of how milk variation is handled. This fix should squash that problem, since this is where the negative values were being introduced.

@JoeWaddell good to know.

**Pull request merged**
