### PR TITLE
Purchased Feed Land Use Change Emissions

### LINKED ISSUE #1639: Duplicate the purchased feed emissions reports
Currently, there is no connection between the feed storage module and the animal module. We are feeding the animals with the purchased feeds. These feeds have emissions associated with them, which we are computing and reporting to the output manager. We want to duplicate these reports. In other words, instead of computing and reporting once, we want to do it twice. The reason for this is that we are waiting for a new set of inputs to arrive, which have an identical format to the existing inputs. By duplicating the logic, we can substitute a set of inputs once we have them.
* This task needs @KFosterReed review before being closed.
* Consider extracting functions and logic where possible.

### PR DESCRIPTION
**Pull request by allisterakun**
Adding a new output to account for `purchased_feed_land_use_change_emissions`.

### Context

Issue(s) closed by this pull request: closes #1639

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

1. Duplicated the current `input/data/EEE/full_feeds_emissions_new.csv` as `input/data/EEE/full_feeds_land_use_change_emissions.csv`
2. Added a new input file in all metadata files: 
```json
"purchased_feed_land_use_change_emissions": {
      "title": "Land Use Change emissions from purchased feeds",
      "description": "Purchased feeds land use change emission values used in the EEE module.",
      "path": "input/data/EEE/full_feeds_land_use_change_emissions.csv",
      "type": "csv",
      "properties": "feed_emissions_properties"
    },
```
3. Added a new property, `PurchasedFeedEmissionsEstimator.purchased_feed_land_use_change_emissions`.
4. Renamed the property `PurchasedFeedEmissionsEstimator.feed_emissions` to `PurchasedFeedEmissionsEstimator.purchased_feed_emissions` for clarification.
5. Renamed `PurchasedFeedEmissionsEstimator._setup_feed_emissions(self) -> dict[str, float]:` to `PurchasedFeedEmissionsEstimator._calculate_feed_emissions(self, feed_emissions_data: Dict[str, List[float]]) -> dict[str, float]:`
    1. Removed the line `feed_emissions_data = im.get_data("purchased_feeds_emissions")`. Receiving this data from input instead makes this a generalized method to handle emission calculation for different parts of the feed production system.
6. Calculating `PurchasedFeedEmissionsEstimator.purchased_feed_land_use_change_emissions` by calling the `PurchasedFeedEmissionsEstimator._calculate_feed_emissions()` function with the newly added "full_feeds_land_use_change_emissions" data.

### Why

To address the emissions produced from land use, change part of the system.

### How

See the What **section**.

### Test plan

There are no unit tests for the `PurchasedFeedEmissionsEstimator` module. Due to the urgency of this issue and considering no major changes made in this PR, I did not create a new test file to cover this module.

Alternatively, I have run this on all (updated) metadata and confirmed that the `purchased_feed_land_use_change_emissions` variable is in the output.

-------------------------------------------------------------
Ed's edit:
For the most part, kept all the changes that Allister made. Changed/added some things though:
- Changed the name `_calculate_feed_emissions` back to `_setup_feed_emissions` but kept the functionality that Allister introduced. My reasoning (which is biased because I wrote the original function) is that it isn't actually calculating anything, it is retrieving and packaging data into a dictionary.
  - Also, I updated the unit test for this method.
- Added the method `create_daily_land_use_change_feed_emissions_report`, which is almost an exact copy of `create_daily_purchased_feed_emissions_report`. This method will create a report containing all the emissions associated with the land use change of purchased feeds.
- Added a call to `create_daily_purchased_feed_emissions_report` in `AnimalModuleReporter.report_daily_feed_emissions`. The emissions associated with the land use change of purchased feeds will now be reported in the same manner as regular(?) purchased feeds emissions.
  - The name of these variables is the same as regular purchased feed emissions, but with "purchased" replaced by "land_use_change"

Also, I have no idea how all those extra changes got in there. I'm sure they're already in `main`, but for some reason they're all listed in this PR too though.

### CODE REVIEW

**Review by ew3361zh — APPROVED** [review]
LGTM. Still not sure I 100% understand the reasoning behind the change but it looks to be doing what the issue is asking to be done and is well implemented. Nice work, Allister!

**Comment by KFosterReed** [comment]
Ok, so apologies for the delayed review on this!

I'll share the good news first...
This does exactly what I had asked for! The new land use change emissions estimates report exactly as desired so when we have the values for those, we can update them with real numbers. 

Here is the less than great news...
I just put two things together and realized that we are kind of duplicating efforts here. The `animal_module_reporter` methods are also reporting purchased feed emissions but aggregating them in a variety of ways. I don't think we should be reporting these values in the Animal module reporter and should migrate these methods to the PurchasedFeedEmissionsEstimator. 

The follow up question is then: can we duplicate all of the methods used for purchased feeds in the AnimalModuleReporter on the new Land Use Change emissions estimates?

**Comment by KFosterReed** [comment]
Ok! I just spoke to the FARM-ES team the functionality in this PR alone is sufficient for their needs so I am going to approve it!

**Review by KFosterReed — APPROVED** [review]

**Comment by KFosterReed** [comment]
Many thanks to Ed for his help to make up for my oversight in this PR and adding the methods to calculate and report the LUC emissions in the Animal Module Reporter!

I retested this on the default inputs as well as c1f1 and c1f3 and it now works as expected including reporting the total emissions as well as the emissons factors :)

@Kaitlyn, I don't think your additional SME review is needed on this PR but I attached two filters if you have time to check my work :)

[report_FARMES_KFR_June5.json](https://github.com/user-attachments/files/15597843/report_FARMES_KFR_June5.json)
[report_purchased_feed_emissions.json](https://github.com/user-attachments/files/15597844/report_purchased_feed_emissions.json)

**Comment by Isgotkowitz** [comment]
@krb78 I think Kristan meant to tag you in her comment. I am going to merge this PR, however if it comes up that there is something incorrect in the calculations, let me know and I will fix it ASAP.

**Pull request merged**
