### PR TITLE
Rebeca c2f12 cs inputs

### PR DESCRIPTION
**Pull request by Rebecavb**
c2f12 crop and soil inputs

### CODE REVIEW

**Review by krb78 — COMMENTED** [review]
Good work Rebeca! :) could I get you to add the following into your metadata because I just updated all the other ones in the pilot branch? 

"purchased_feed_land_use_change_emissions": {
      "title": "Land Use Change emissions from purchased feeds",
      "description": "Purchased feeds land use change emission values used in the EEE module.",
      "path": "input/data/EEE/full_feeds_land_use_change_emissions.csv",
      "type": "csv",
      "properties": "feed_emissions_properties"
    },

**Comment by Rebecavb** [comment]
> Good work Rebeca! :) could I get you to add the following into your metadata because I just updated all the other ones in the pilot branch?
> 
> "purchased_feed_land_use_change_emissions": { "title": "Land Use Change emissions from purchased feeds", "description": "Purchased feeds land use change emission values used in the EEE module.", "path": "input/data/EEE/full_feeds_land_use_change_emissions.csv", "type": "csv", "properties": "feed_emissions_properties" },

Yes ofc. Is there any specific location inside the metadata that you want me to put it?

**Comment by krb78** [comment]
anywhere you'd like within the metadata is perfect - for ease, I'll admit, I ended up adding it at the beginning to many of the metadata files :)

**Comment by Rebecavb** [comment]
> Current Coverage: 95%
> 
> Mypy errors on rebeca_c2f12_cs_inputs branch: 3540 Mypy errors on main branch: 3540 No difference in error counts

@jadamchick Do you know what is this error for?

**Comment by Isgotkowitz** [comment]
> > Current Coverage: 95%
> > Mypy errors on rebeca_c2f12_cs_inputs branch: 3540 Mypy errors on main branch: 3540 No difference in error counts
> 
> @jadamchick Do you know what is this error for?

@Rebecavb this isn't actually an error. This is an automated message telling you the number of [Mypy](https://github.com/RuminantFarmSystems/MASM/wiki/Using-Mypy) errors that are your branch and in the main branch. Since you're not merging any code into main, you can ignore this message.

**Comment by Rebecavb** [comment]
> > > Current Coverage: 95%
> > > Mypy errors on rebeca_c2f12_cs_inputs branch: 3540 Mypy errors on main branch: 3540 No difference in error counts
> > 
> > 
> > @jadamchick Do you know what is this error for?
> 
> @Rebecavb this isn't actually an error. This is an automated message telling you the number of [Mypy](https://github.com/RuminantFarmSystems/MASM/wiki/Using-Mypy) errors that are your branch and in the main branch. Since you're not merging any code into main, you can ignore this message.

Thanks @Isgotkowitz . How do I remove this message from the pull request? Right now I am not able to merge the branch to pilot testing because of that message

**Comment by Isgotkowitz** [comment]
> > > > Current Coverage: 95%
> > > > Mypy errors on rebeca_c2f12_cs_inputs branch: 3540 Mypy errors on main branch: 3540 No difference in error counts
> > > 
> > > 
> > > @jadamchick Do you know what is this error for?
> > 
> > 
> > @Rebecavb this isn't actually an error. This is an automated message telling you the number of [Mypy](https://github.com/RuminantFarmSystems/MASM/wiki/Using-Mypy) errors that are your branch and in the main branch. Since you're not merging any code into main, you can ignore this message.
> 
> Thanks @Isgotkowitz . How do I remove this message from the pull request? Right now I am not able to merge the branch to pilot testing because of that message

So that is actually not why your PR is blocked from merging. It is because there is a conflict between the README files on your branch and the pilot testing branch. This thing:
image

There are a million different ways to fix this, but I'm not sure which way will be most comfortable for you. If you'd like, we can hop on a call and I can walk you through how to do it. Otherwise I could just take care of it for you, lmk what works best

**Review by krb78 — APPROVED** [review]

**Pull request merged**
