### PR TITLE
new life-cycle module code

### PR DESCRIPTION
**Pull request by manfei-L**
Please wait until next commit with comments and document uploaded to review

### CODE REVIEW

**Comment by KFosterReed** [comment]
I can generally follow what you are doing and how you've separated the life cycle into different files based on animal class. My biggest comment is that you need more comments! I know you know this but it is so important so it is worth repeating. Max has done a great job modeling the commented information that should be at the top of each file explaining what each file does and what information is needed as inputs, what variables are only used within the file, and what the outputs are. You are the best person to do this so before merging I would definitely like that to happen. Please and thank you!

A couple of specific questions: 

In cow.py: 

L 91 and elsewhere ... I would prefer if you call the milk production in the life cycle module as estimated_daily_milk_prod or something like that to differentiate it from the final actual milk production. This will be something to communicate with Militsa about and potentially could be something she does this summer as well

L110 Why are you estimating DMI? Did we decide that was something you were supposed to estimate and send to the ration module? I can't remember. 

You have a lot of return commands, are these for your benefit? Will they be removed? I would like to come up with some sort of notation to indicate parts of the code that are for your code development/checking and won't be in the final model. 

You have a lot of 'econ stats' that are being recorded and updated. I prefer not to think of these as economics stats but performance stats because these have potential to be used for things besides economics. Why are these stats recorded in a different manner to other output information? 

There is a lot of replication between cow.py and heiferII.py for the reproduction and pregnancy routines. Is it possible to have a generic reproduction and pregnancy file/function that is called with separate parameters for heifers and cows?

Overall, you've done a lot of work and it is great that the model runs and gives reasonable outputs. Now we need to put the finishing touches on it to make sure it adheres to RuFaS standards :)

**Comment by manfei-L** [comment]
Comments added, ready for review
[animal life cycle flowchart.pdf](https://github.com/RuminantFarmSystems/MASM/files/3108959/animal.life.cycle.flowchart.pdf)
[animal life time line.pdf](https://github.com/RuminantFarmSystems/MASM/files/3108962/animal.life.time.line.pdf)

**Comment by manfei-L** [comment]
Hi Kristan,

I added comments and addressed the points you mentioned. 
I also marked TEMP for those cost and income values to indicate those are for the code validation and will be altered in the future with ration formulation and econ module.

**Comment by manfei-L** [comment]
@KFosterReed @vecabrera @militsasotirova @wmdonovan-uwcs

**Review by militsasotirova — APPROVED** [review]
This looks good to me! I really like the flow chart - it helped me understand the code more.

**Review by vecabrera — APPROVED** [review]
I have gone over all code with Manfei and we made some improvement changes. The structure of the code makes a lot of sense. We can now start testing the results by manipulating the inputs.

**Review by wmaxdonovan — APPROVED** [review]

**Review by KFosterReed — APPROVED** [review]

**Comment by manfei-L** [comment]
Implemented in new animal management structure, pull request closed.

**Pull request closed without merging**
