### PR TITLE
Add daily sell info

### PR DESCRIPTION
**Pull request by PooyaHekmati**
This PR addresses issue #1067 by adding the `sold_at_day` variable to the base animal and populating it when a HeiferII, HeiferIII, or Cow is sold. Then, in animal module reporter, uses this value to compile a list of daily sales and reports how many animals were sold and how much they weighed to OM. Adds the following keys to OM:
```
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferII_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferII_sold_weight
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferIII_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferIII_sold_weight
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.sold_and_died_cows_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.sold_and_died_cows_sold_weight
```

This is needed urgently, will do the tests later.

### CODE REVIEW

**Review by jadamchick — CHANGES_REQUESTED** [review]
I used these filters to look at the outputs in a csv: 
```
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferII_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferII_sold_weight
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferIII_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferIII_sold_weight
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.sold_and_died_cows_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.sold_and_died_cows_sold_weight
AnimalModuleReporter.report_sold_animal_information.*
LifeCycleManager.daily_update.*
```

The number of entries in each of the "sold_count" and "sold_weight" columns is not identical, and is not the same as the number of sim_days -- so I'm not comfortable assuming that each row is a day. That said, there are LifeCycleManager.daily_update values for # of animals sold/d (heiferII, heiferIII) and those totals over the whole simulation align with the totals of each of your "sold_count" columns respectively. 

Rather than focusing on fixing those wrinkles right now, I think the easiest solution (that I already tested and works for me) is to add "sold_day" to the outputs included in AnimalModuleReporter.report_sold_animal_information. 

Then I can use the following report filter to get the list of all animals sold and aggregate manually using sold_day as a guide for when they were sold. 
```
{
            "name": "Animals sold in the whole simulation",
            "filters": [
                "AnimalModuleReporter.report_sold_animal_information.(animal_id|animal_type|body_weight|sold_day)"
            ]
        } 
```

**Comment by PooyaHekmati** [comment]
> The number of entries in each of the "sold_count" and "sold_weight" columns is not identical, 

I'm not sure if I'm fully understanding what are the things that need to be identical and are not.

>so I'm not comfortable assuming that each row is a day.

Each row is a day.

>That said, there are LifeCycleManager.daily_update values for # of animals sold/d (heiferII, heiferIII) and those totals over the whole simulation align with the totals of each of your "sold_count" columns respectively.

```
         (__)
         (oo)
  /-------\/
 / |     ||
*  ||----||
   ^^    ^^

```
 
The animal reporter was cropping the results to the first and last sell event, I changed it to cover the whole simulation length. I also added a few new entries to the OM. Can you retry using the CSV filter below?

```
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferII_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferII_sold_weight
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferIII_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferIII_sold_weight
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.sold_and_died_cows_sold_count
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.sold_and_died_cows_sold_weight
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferII_first_sell_event
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferII_last_sell_event
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferIII_first_sell_event
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.heiferIII_last_sell_event
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.sold_and_died_cows_first_sell_event
AnimalModuleReporter.report_sold_animal_information_sort_by_sell_day.sold_and_died_cows_last_sell_event
SimulationEngine.simulate.day_counter_final_value
```

**Review by jadamchick — APPROVED** [review]
Hi Pooya - this works better! When my simulation is 1116 days long, all of the "counts" and "weights" columns have 1116 rows, and events align with the days reported by the first and last sell event values. 
When I use it in the report filter, I can use slice_start: -365 and it only gives me 365 entries, and the values reported are the same as those summarized in the LifeCycleManager daily updates. 

There are a couple more would-be-nice features (to include calves, and to update the cows reported to be only cows sold, not sold_and_died). I'll make an issue about that so we can revisit it in January. This will work fine for now. Thank you!

**Comment by jadamchick** [comment]
Follow up on those "would be nice" updates for someday: https://github.com/RuminantFarmSystems/MASM/issues/1076

**Pull request merged**
