### PR TITLE
proposed gestation_length bug fix

### PR DESCRIPTION
**Pull request by JoeWaddell**
Related to Issue #1078, it appears that some animals were being skipped in their promotion from heifer II to III, which ultimately led to decreasing body weights and crashing the simulation.

By changing `==` to `>=` in the statement `if self.days_in_preg >= self.gestation_length - AnimalBase.config["prefresh_day"]:`, it seems to catch this edge case. 

With this potential fix, I'm unable to find cases of days_in_preg going over the gestation_length, or with negative body_weights/requirements. 

I'm curious if others can chime in as to whether the decrease in days_born (a few lines following the statement I quoted above) is an error, and if it might be leading it to occasionally miss other checks.

Finally, ignore the print statements! Prior to the change here they'd show the errors, so I left them in as a way to check that the fix is working.

### CODE REVIEW

**Comment by jadamchick** [comment]
Hi Joe,
This keeps getting more strange and complex. 
When I run the default scenario (no changes to anything) on this branch, the herd dynamics are way off. (I tried the default, because I was running pilot herds and they were all looking funky). 
I repeated with the defaults but changing "prefresh_day" value back to 30, and the results were no different. 

image


& this is aggregated (average) over the last year: nearly 100% of cows are L4. 
image


I haven't dug much deeper into why; I'm still incredulous that changing one line in the heiferII.py would lead to this. 
Maybe @KFosterReed or @krb78 or @ltp23 would have some ideas?

**Comment by JoeWaddell** [comment]
This is a tricky one, and I see the same behavior on my end. This change seems to eliminate heifer IIIs entirely, from the start of the simulation, in addition to slowly weeding out heifer IIs. I'll keep digging into why this might be the case, but it is at least diagnostic.

**Comment by JoeWaddell** [comment]
Updated with a slight logic fix.

Prior to animals being assigned a gestation_length they have the value of 0.0, which is why the previous 'fix' I tried didn't work. It would immediately attempt to promote heifer IIs to heifer IIIs, and I suppose those animals were missing attributes necessary to make them act as functioning lactating cows, and were perhaps immediately changed to dry cows?
This all gets back to the more general need we have for refactoring inheritance and these animal classes.

**Comment by jadamchick** [comment]
Looks better! I ran this using the animal files for 2 of the pilot farms that were throwing the original error (c2f11 and c2f18) and they both run full simulations now. 
However, (thanks to your print statements!) it looks like c2f18 still has occasions of body weight decreases and negative P_req's. 
It is a herd of 440 adult cows and I ran it for 6 years, to give you a sense of frequency. Happy to share the .json with you if you'd like to dig deeper into this case. 

Here is what printed in the terminal: 
p_req = -257.5877252834541
body_weight = 405.4775436472001
id = 249
preq bug!
p_req = -258.281659463329
body_weight = 404.40646156988805
id = 249
/preq bug!
p_req = -7.254255619235108
body_weight = 465.89388367935845
id = 226
preq bug!
p_req = -6.371024784403466
body_weight = 464.15662673994456
id = 226
preq bug!
p_req = -5.549384174407462
body_weight = 462.49855639590857
id = 226
preq bug!
p_req = -4.783721231340934
body_weight = 460.914345549016
id = 226
preq bug!
p_req = -4.069049788750549
body_weight = 459.39913588567697
id = 226
preq bug!
p_req = -3.400927883942029
body_weight = 457.9484873297324
id = 226
preq bug!
p_req = -2.7753878971402783
body_weight = 456.55833390505705
id = 226
preq bug!
p_req = -2.1888769468290343
body_weight = 455.2249450785559
id = 226
preq bug!
p_req = -1.6382058541740752
body_weight = 453.9448918051148
id = 226
preq bug!
p_req = -1.1205052956000556
body_weight = 452.71501661999264
id = 226
preq bug!
p_req = -0.6331880082024053
body_weight = 451.5324072262987
id = 226
preq bug!
p_req = -0.1739161106560635
body_weight = 450.39437310975165
id = 226

**Comment by JoeWaddell** [comment]
@jadamchick I'm hoping that will be fixed by PR #1133 , but we'll see once we merge it to main (and update this branch).

**Comment by jadamchick** [comment]
> @jadamchick I'm hoping that will be fixed by PR #1133 , but we'll see once we merge it to main (and update this branch).

Fantastic. LMK if/when it'd be helpful for me to re-run anything on my end.

**Comment by JoeWaddell** [comment]
PR now catches the bug that was causing #1078 , however I've also opened #1166 to address the other bug noted in this series of comments (a few animals dropping in weight unexpectedly). I will restore the default `prefresh_day` of 30 prior to merge to main.

**Review by jadamchick — APPROVED** [review]
Runs well for c2f11 and c2f18, no errors!

**Comment by ltp23** [comment]
It is possible for a heiferII to enter the herd from initialization and have `days_in_preg > gestation_length - prefresh_day`. An example I saw was

Days in preg =  242
Gestation length = 281
Prefresh day = 60

An alternative way to do the checking is using 3-way comparison:

```
if self.days_in_preg >= self.gestation_length - AnimalBase.config["prefresh_day"] > 0:
```

It is good to check that `days_in_preg` is positive or != 0 (like Joe did) because I saw a case where both days-in-preg and gestation-length were both 0 but with negative prefresh-day, I got True for the expression `days in preg > gestation length - prefresh day`.

**Comment by ltp23** [comment]
Here is the filter file I used

```
{
  "multiple": [
    {
      "type": "plot",
      "filters": [
        "LifeCycleManager.daily_update.avg_cow_body_weight"
      ],
      "title": "Average Cow Body Weight",
      "legend": [
        "Average Cow Body Weight"
      ]
    },
    {
      "type": "plot",
      "filters": [
        "AnimalManager._calc_ration_at_interval.avg_rqmts_pen_1_GROWING",
        "AnimalManager._calc_ration_at_interval.avg_rqmts_pen_2_CLOSE_UP",
        "AnimalManager._calc_ration_at_interval.avg_rqmts_pen_3_LAC_COW"
      ],
      "variables": [
        "P_req"
      ],
      "title": "Average P_req",
      "legend": [
        "P_req pen 1",
        "P_req pen 2",
        "P_req pen 3"
      ]
    }
  ]
}
```

**Comment by ltp23** [comment]
I merged main into this branch, just in case.

**Review by ltp23 — APPROVED** [review]

**Pull request merged**
