### PR TITLE
Fixed the double counted MP in NLP

### PR DESCRIPTION
**Pull request by tomhuhh**
Also added a TODO: Separate the DMI components from MPm requirements calculated by both NRC (2001) and NASEM (2021) and put them in this section because DMI gets reestimated during each iteration.

### CODE REVIEW

**Review by Ed731551 — APPROVED** [review]
Implemented changes make sense to me according to previous discussions.

**Comment by tomhuhh** [comment]
Hello @KFosterReed! The issue described in Issue #567 is addressed here. There currently seems to be no unit test for the modified function `def protein_constraint(x):`. Other than that, the duplicate section has been deleted from this function in the NLP.py file and a TODO and a new issue #572  are created. Please let us know what your thoughts are. Thanks!

Screenshot 2023-06-13 at 4 02 25 PM

**Review by Ed731551 — APPROVED** [review]

**Review by JoeWaddell — CHANGES_REQUESTED** [review]
Looks good, I just think we should remove the TODO and make it an issue, instead.

**Comment by tomhuhh** [comment]
Add issue #622.

**Review by JoeWaddell — APPROVED** [review]

**Pull request merged**
