### PR TITLE
Utility class

### PR DESCRIPTION
**Pull request by ltp23**
Hi everyone,

For this small pull request, I created a Utility class and then moved some general functions like `get_base_dir` and `read_json_file` into it. I also fixed some old references and import statements related to those functions.

### CODE REVIEW

**Review by PooyaHekmati — APPROVED** [review]
Granted, there is room for improvement here, but I don't think it is our priority right now. So, lgtm.

**Review by KFosterReed — COMMENTED** [review]
This looks good to me! The changes are clear and the new Utility class will be great to have as we expand the functions that are most appropriate to be housed here for use throughout the model. Nice work!

One question before I approve: There are a couple of functions (calc_average, remove_items_from_list, etc) that I don't see where they are used. My thought is maybe you are using them in other branches? Is that correct? And, I know that at least in the animal module there are current functions that could be replaced by these functions. If that is also correct, I think it would be a good idea to make a git issue related to updating functions that can be replaced with the utility functions in this pull request. Thoughts?

**Comment by rhensen** [comment]
Yeah I approve this as well but will let you respond to Kristen's comment before approval.

**Review by KFosterReed — APPROVED** [review]
Talking to Loi on Slack, he told me where the functions are used in his life cycle refactoring branch so I am happy with this work

**Pull request merged**
