### PR TITLE
Deobfuscate Animal Module output

### LINKED ISSUE #1160: Deobfuscate Animal Module Reporter output
The Animal Module provides a significant amount of output to the OutputManager through the `AnimalModuleReporter` class. Most of the outputs have info maps that are not populated with the actual class and function that are doing the recording though. They are populated with the class and function in the Animal module that are responsible for maintaining/modifying/updating those values. This behavior is problematic, because it obscures the location where the output is being recorded.

Potential solution:
- Add a new entry to info_map: a list of tuples called _data_origin_. Each tuple contains 2 elements: originating class, originating function.
- Make the class and function in the info map point to the actual location where the data is being added to the OutputManager.

Note that this issue is addressing the same underlying problem as #1148. The solution to these two issues should ultimately be the same.

### PR DESCRIPTION
**Pull request by Isgotkowitz**
This PR modifies the info maps in `AnimalModuleReporter` so that the "class" and "function" fields reflect where the data is being recorded instead of where it is being generated/modified, as was previously done. The place where data is generated/modified is now recorded as a tuple in the info map, under the key "data_origin".

All AnimalModuleReporter tests have been modified appropriately.

Closes #1160

### CODE REVIEW

**Review by allisterakun — APPROVED** [review]
Simple and straight forward changes, good job, Ed!

**Review by PooyaHekmati — APPROVED** [review]
Nicely done!
Can you please make a follow up issue so that when OM sees `data_origin` it gives it special attention? I'm not sure about the details, but it seems like the next logical step here.

**Review by JoeWaddell — APPROVED** [review]
LGTM

**Comment by Isgotkowitz** [comment]
This PR SHOULD NOT be merged before 2/13.

**Comment by PooyaHekmati** [comment]
> This PR SHOULD NOT be merged before 2/13.

why?

**Comment by Isgotkowitz** [comment]
> > This PR SHOULD NOT be merged before 2/13.
> 
> why?

@PooyaHekmati because Haowen is extracting data for a report that has a deadline of the 13th. I want to holdoff on merging this until then so he can focus on analyzing the data instead of spending a bunch of time rewriting his reports.

**Review by jadamchick — APPROVED** [review]
Hi Ed, this looks logical and clean, and was an easy update to switch over my report filters. Thanks!

**Pull request merged**
