### PR TITLE
Update `check_changes` scripts to work with `dev` branch

### PR DESCRIPTION
**Pull request by Isgotkowitz**
See title

### Context

Issue(s) closed by this pull request: closes N/A

I will also update the Wiki when this gets merged.

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

Changed the `check_changes.sh` script, and the `check_changes.bat` file to do their thing on the `dev` branch instead of the `main` branch.

### Why

With the introduction of the new branching structure (merging to `dev`, then testing changes in `test` before merging periodically to `main`), the scripts need to be updated so that they can be used with as little effort as possible.

### How

Replaced the term "main" with "dev".

### Test plan

Made a trivial flake8 error on a branch, then ran `check_changes.sh` to verify that it caught the error. Same thing on Windows with the .bat script.

### CODE REVIEW

**Review by ew3361zh — APPROVED** [review]
Works well for me on a Mac. Other review should probably come from someone running it on Windows to ensure they both work as designed. Nice work, Ed!

**Review by matthew7838 — COMMENTED** [review]
```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Scripts\flake8.exe\__main__.py", line 7, in <module>
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\cli.py", line 23, in main
    app.run(argv)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 198, in run
    self._run(argv)
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 187, in _run
    self.run_checks()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 103, in run_checks
    self.file_checker_manager.run()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\checker.py", line 236, in run
    self.run_parallel()
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\checker.py", line 205, in run_parallel
    self.results = list(pool.imap_unordered(_mp_run, self.filenames))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 873, in next
    raise value
IndexError: string index out of range
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Missing target module, package, files, or command.
```
  an into such exception, not sure if it's my problem or there's a problem. I switch to this branch and run .\check_changes.bat

**Comment by Isgotkowitz** [comment]
> ```
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in _run_module_as_main
>   File "<frozen runpy>", line 88, in _run_code
>   File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Scripts\flake8.exe\__main__.py", line 7, in <module>
>   File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\cli.py", line 23, in main
>     app.run(argv)
>   File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 198, in run
>     self._run(argv)
>   File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 187, in _run
>     self.run_checks()
>   File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\main\application.py", line 103, in run_checks
>     self.file_checker_manager.run()
>   File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\checker.py", line 236, in run
>     self.run_parallel()
>   File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\site-packages\flake8\checker.py", line 205, in run_parallel
>     self.results = list(pool.imap_unordered(_mp_run, self.filenames))
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\matth\AppData\Local\Programs\Python\Python312\Lib\multiprocessing\pool.py", line 873, in next
>     raise value
> IndexError: string index out of range
> usage: mypy [-h] [-v] [-V] [more options; see below]
>             [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
> mypy: error: Missing target module, package, files, or command.
> ```
> 
> an into such exception, not sure if it's my problem or there's a problem. I switch to this branch and run .\check_changes.bat

Huh, that is weird. I haven't been able to reproduce this error, did you run it in the Windows Cmd terminal or PowerShell? It also might have to do with the version, I have Python 3.11 on my Windows, not 3.12. Did this error pop up immediately or did the script take a long time to run and error out?

**Review by matthew7838 — APPROVED** [review]

**Comment by Isgotkowitz** [comment]
@ew3361zh and @matthew7838 thank you for the reviews!

**Pull request merged**
