### PR TITLE
Database usage for feed library

### PR DESCRIPTION
**Pull request by militsasotirova**
I've replaced the usage of the feed CSV file with a database and I interacted with the database through PyCharm. I think the program should automatically connect to the sqlite file that I added to the Inputs folder.

I’ve deleted the old feed libraries and put the newest one that we had been working with (manure_feed_test.csv) into the database file feeds.sqlite. I’ve also deleted testing_manure.json, testing_ration.json, and input_w_feedlib.json as I don’t believe we have a use for them anymore (from a quick glance, I realized they have exactly the same input information as animal_management.json). 

I mainly worked in feed.py to add some data structures to store the feed information. However, I did delete the class that we had to previously store the feed information (util.Library) because that was its only usage and replaced it with the NutrientValues class in feed.py. If it turns out that we need Library for something else we should put it back in, but for now since we don't use it I don't think we benefit from having it there.

Also, I learned that you can type objects in Python (see some of the methods in the Feed class). I don't know if we want to incorporate this into our standards or we should just use it if we feel that a method would benefit from the extra clarity.

One of the topics I plan on addressing in the animal module meeting is that of the nutrient names. In Python the convention for enums seems to be UPPER_CASE and currently that is not the case with the nutrient names. There also seems to be a lot of redundancies (i.e. dRUP_RUP, dStarch_Starch_base, dFA_FA_base, etc) that don’t really have obvious meaning.

### CODE REVIEW

**Review by wmaxdonovan — COMMENTED** [review]
If we're planning on keeping databases for other elements of the model as well as feed we should consider consolidating database management code like we have for output handling. It's confusing in the object/driver for feed, especially because there are now two classes defined in that file, one called Feed and one called Feeds. What data are we trying to keep? Input, output, intermediate? If we are only interested in input and output then the database can function on the outside of the existing model by operating on the input files/initialized objects and the csv s at the end. Even if we are interested in storing intermediate variables, the output handler has a method for accessing those variables that works well. I don't know if we want to mix database and csv output code or keep them separate, but we're likely accessing a lot of the same information and could cut down on code and files. This is completely about model flow and organization but I think it's important as we add database management for other features.

**Comment by militsasotirova** [comment]
Thank you for your suggestions! 
I made the usage of databases as a way to store inputs more generalized with a class called DatabaseReader in util.py. Currently, only the feed library is read in this way, but it should be easy to do the same for other csv inputs. I also renamed Feeds to FeedNames for clarity.
 
I think this pull request is now ready. Let me know if there is anything else that needs clarification/modification.

**Review by wmaxdonovan — APPROVED** [review]
I really like the consolidation in the new changes. This is a great addition and I think we should be adding similar database management to all modules. We can do that for soil and crop, but maybe also time to start thinking about a centralized database management hierarchy? i.e. a structure for maintaining overall input/output for runs over time.

**Review by Jacob8399 — APPROVED** [review]
I agree with Max about the general database management hierarchy and I am very excited to see this added to RuFaS. I don't see any specific problems besides it saying there are some conflicts with a few of the JSON files.

**Comment by militsasotirova** [comment]
Thanks for your comments! Thinking about an overall organization for general database management is something that we are planning on discussing at our data management meetings.

**Review by tlh96 — APPROVED** [review]

**Pull request merged**
