### PR TITLE
Expanding NASEM Comp with TDN

### PR DESCRIPTION
**Pull request by JoeWaddell**
Following advisement from Haowen and Edward, I've expanded the temporary NASEM_Comp_with_TDN.csv (see Issue #834) with items with a `Fd_Category` of `Vitamins/Minerals`, giving them a TDN of 0.0.

I've also updated `user_feeds.csv` to reflect where each feed item can be found (NASEM only, NRC only, or both).

Note that all of those have a `Feed_type` of Conc: I want to be sure this is valid, given the `Feed_type` in `user_feeds.csv`.

### CODE REVIEW

**Review by tomhuhh — APPROVED** [review]
LGTM! Thanks Joe!

**Comment by KFosterReed** [comment]
Hey team, I was looking at some outputs from a pilot test tonight and realized that the relationship between the DM amount and As Fed amount was off which led me to the small changes in the ration driver... As fed (kg) = DM(kg)/(DM%/100) where as previously it was  As fed (kg) = DM(kg) * (DM%/100). I think I even successfully updated the unit test? 

Sneaking this in here probably isn't best practice but I thought adding it to an already small PR was acceptable if not just a minor sin.

**Review by KFosterReed — APPROVED** [review]

**Comment by JoeWaddell** [comment]
The change from multiplication to division led to a divide by 0 error (for when available feeds aren't present in a given ration), so I made a quick fix here. Should be good to merge, but I'll wait until @KFosterReed or @tomhuhh can take a quick look again, just to double-check this fix on top of a fix!

**Review by KFosterReed — APPROVED** [review]
Good catch Joe!

**Review by Ed731551 — COMMENTED** [review]
To me implemented logic makes sense. Thanks

**Pull request merged**
