### PR TITLE
[Report Generator] No aggregation reports

### PR DESCRIPTION
**Pull request by PooyaHekmati**
This PR mainly focuses on allowing users to provide a report filter with no aggregation. Previously, we handled this case by raising an error. The user might be interested in this feature as it allows them to slice data, assign labels to it, and save it along with aggregated data in the same CSV file.
If data is being aggregated, we now append `hor_agg`, `ver_agg`, `ver_hor_agg`, or `hor_ver_agg` to the column name to denote the aggregation.
The PR also makes some minor improvements in terms of code organization in `RG.generate_report()`.

### CODE REVIEW

**Review by jadamchick — APPROVED** [review]
Works great! 

I used this filter: 
{
    "name": "Animals sold in the last year",
    "filters": ["AnimalModuleReporter.report_sold_animal_information.(animal_id|animal_type|body_weight)"],
    "slice_start": -365
 }

And got exactly the info I wanted. 
And when I included that within a report with multiple filters, it also worked nicely and included these values logically in the csv output. 
The tags on the labels of the aggregated columns (eg "ver_agg") also work well. 

I did notice that when a filter leads to empty report data, it halts the production of all reports (it used to report this in the errors file but continue to generate all of the reports for which it could locate the data). I preferred the previous, so that I would still get the majority of the reports (and the logs, warnings, etc. files to help me troubleshoot if needed).

**Comment by PooyaHekmati** [comment]
> I did notice that when a filter leads to empty report data, it halts the production of all reports (it used to report this in the errors file but continue to generate all of the reports for which it could locate the data). I preferred the previous, so that I would still get the majority of the reports (and the logs, warnings, etc. files to help me troubleshoot if needed).

Thanks for catching that. It should be fixed now, can you please give it a second look?

**Comment by jadamchick** [comment]
> > I did notice that when a filter leads to empty report data, it halts the production of all reports (it used to report this in the errors file but continue to generate all of the reports for which it could locate the data). I preferred the previous, so that I would still get the majority of the reports (and the logs, warnings, etc. files to help me troubleshoot if needed).
> 
> Thanks for catching that. It should be fixed now, can you please give it a second look?

Yes, it works as expected now. Thank you!

**Review by Isgotkowitz — APPROVED** [review]
Code looks good to me. I tried creating some new reports and worked well - this is going to be a really handy feature.

**Pull request merged**
