### PR TITLE
Update unit for purchased feed emissions

### LINKED ISSUE #1909: [Feed] Unit Error on actual_purchased_feed_emissions and actual_land_use_change_emissions
I'm a bad 🐒 and when I reviewed this PR the first time I missed that the units are wrong on this... 

I believe we are calculating KILOGRAMS CARBON DIOXIDE instead of KILOGRAMS_CARBON_DIOXIDE_PER_KILOGRAM_DRY_MATTER

## Expected Behavior
Everything works great, it's just a minor unit change that I noticed when I ran a report with the new ability to pull units into the report. 

I'm quite sure we are reporting total kg, not kg/kg DM - this is purely based off of my judgement as to how big emissions might be per kg DM (and the fact that when we report feed emissions otherwise they are reported in kg). 

## Target Deadline
none really, this is a teeny tiny fix that shouldn't take too long.

### PR DESCRIPTION
**Pull request by ew3361zh**
This PR updates the unit for emissions related to purchased feeds from `KILOGRAMS_CARBON_DIOXIDE_PER_KILOGRAM_DRY_MATTER` to `KILOGRAMS_CARBON_DIOXIDE_EQUIVALENT`.

It also updates `KILOGRAMS_CARBON_DIOXIDE_EQ` to `KILOGRAMS_CARBON_DIOXIDE_EQUIVALENT` for clarity.

### Context

Issue(s) closed by this pull request: closes #1909

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

A simple unit update for purchased feed emissions being logged to OM.

### Why

The previous unit was incorrect

### How

Unit name was updated.

### Test plan

Run a simulation on this branch and look at output variable names list to see the new updated unit for purchased feed emissions:
Screenshot 2024-08-16 at 10 07 53 AM

### CODE REVIEW

**Review by krb78 — APPROVED** [review]
pure perfection! and hopefully quick and easy on your end. Thanks, Niko :)

**Review by Isgotkowitz — COMMENTED** [review]
I hate to throw a big monkey wrench in this PR, but I think the units are actually kg emissions / kg dry matter. The variables that are recorded in the `__init__` routines of `PurchasedFeedEmissionsEstimator` are the emissions factors for different RuFaS Feeds, not the actual emissions amounts. (These output variables named).

If these units were actually just kg of CO2 equivalent emissions, I am not sure the results coming out of the methods `create_daily_purchased_feed_emissions_report` and `create_daily_land_use_change_feed_emissions_report` would make much sense - these methods multiply the kg of dry matter in a ration by the emissions factor, and the result has the units of kg CO2 equivalent. If the units of the factors was just kg CO2, then the result of these methods would have units of kg dry matter * kg CO2 equivalent emissions.

Tagging @krb78

**Comment by krb78** [comment]
Hmmm you are right Ed... but the output filter when it runs with the unit report must not be doing the kg CO2e/kg DM * kg DM logic correctly, because it's only showing kg CO2e / kg DM as the units.

**Comment by ew3361zh** [comment]
> Hmmm you are right Ed... but the output filter when it runs with the unit report must not be doing the kg CO2e/kg DM * kg DM logic correctly, because it's only showing kg CO2e / kg DM as the units.

@krb78 which output filter specifically? I'd be happy to take a look. It might be another unit that needs to be adjusted so that it will properly reduce/simplify.

**Comment by Isgotkowitz** [comment]
> Hmmm you are right Ed... but the output filter when it runs with the unit report must not be doing the kg CO2e/kg DM * kg DM logic correctly, because it's only showing kg CO2e / kg DM as the units.

@krb78 I assume you are referring to the outputs that @ew3361zh included in his screenshot in the PR description:
```
PurchasedFeedEmissionsEstimator.__init__.purchased_feed_emissions.1 (kg CO2 / kg DM)
PurchasedFeedEmissionsEstimator.__init__.purchased_feed_emissions.2 (kg CO2 / kg DM)
...
```
These are the factors that are used for the emissions calculations, not the actual emissions amounts themselves.
To see the actual amounts of emissions associated with feeds being given to animals, the following variables should be looked at:
```
AnimalModuleReporter.report_daily_feed_emissions.purchased_feed_emissions_Pen_0_animal_CALF_.202 (kg CO2-eq)
...
AnimalModuleReporter.report_daily_feed_emissions.purchased_feed_emissions_Pen_1_animal_GROWING_.2 (kg CO2-eq)
...
AnimalModuleReporter.report_daily_feed_emissions.purchased_feed_emissions_across_pens.202 (kg CO2-eq)
...
```

I aplogize for the output names, they are really not reflective of the actual values they are outputting.

**Comment by krb78** [comment]
Oh man @Isgotkowitz, you are making me feel like a crazy person. I originally brought this issue up because when I was reviewing the report outputs, it had kg CO2e / kg DM, but I see what you are saying... which is mostly that I made poor @ew3361zh do work that wasn't necessary. 🤦🏻

**Comment by ew3361zh** [comment]
After discussion 8/27, @krb78 will re-run a simulation using the current units and will determine if this change is still necessary.

**Comment by ew3361zh** [comment]
As mentioned in the issue #1909, this was reviewed by @Isgotkowitz and @krb78 and was determined to be correct as is so no changes will be implemented and this PR will be closed without merging.

**Pull request closed without merging**
