### PR TITLE
Save Metadata to CSV patch

### LINKED ISSUE #1512: [IM] Add feature to generate list of inputs
`OutputManager` automatically produces a file containing all the output variables. Here we want to replicate the functionality for inputs.

### PR DESCRIPTION
**Pull request by ew3361zh**
Short patch to address some issues with the `save_metadata_properties()` (formerly `dump_metadata_properties()`) PR #1555.

### Context

Issue(s) closed by this pull request: closes #1512

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
- [X] How big are the changes in the PR? Would you nominate it for a major version upgrade? Minor, no version upgrade.

### What

Addressing some concerns raised by @PooyaHekmati in PR #1555:
1. IM logs have been added for attempting to save the CSV metadata properties (and exception handling has been added and had testing added as well).
2. The function to save the metadata properties as a CSV has been renamed to `save_metadata_properties()` (pka `dump_metadata_properties()`).

### Why

The naming is now clearer as to the functionalities each of these methods executes and it is a requirement of the IM to log its activities to OM.

### How

The naming was updated by searching the associated files and testing and ensuring all references were updated.

### Test plan

Testing has been updated to ensure coverage is maintained at the same level and that all references to functions are updated.

### CODE REVIEW

**Review by allisterakun — APPROVED** [review]
Straight-forward PR. Great job Niko!

**Review by ltp23 — APPROVED** [review]
LGTM. Thanks, Niko.

I noticed the names of the log files are not prefixed. Maybe it is not part of the `-a` gnu arg. Can you also check how the task manager will integrate with this PR?

**Comment by ew3361zh** [comment]
> LGTM. Thanks, Niko.
> 
> I noticed the names of the log files are not prefixed. Maybe it is not part of the `-a` gnu arg. Can you also check how the task manager will integrate with this PR?

Good points, Loi. I can try to take care of the prefix issue and I believe this is functioning correctly in main right now but I will make sure it continues to function as intended with these changes. Thank you!

**Comment by PooyaHekmati** [comment]
Reverted the merge via PR #1605 as the docstring is wrong.
Either have a one-liner or have a complete docstring. The current docstring is missing raises section.

**Pull request merged**
